---
title: "Menus"
format: html
editor: visual
---

https://www.buywholefoodsonline.co.uk

#### 1 Monday 15-01-2024 to Sunday 21-01-2024

**Mon**: Chickpea and red pepper tray bake + broccoli (Iyer Express)

**Tue**: fish curry, rice and broccoli (Sodha Made in India)

**Wed**: Cauliflower, potatoes and peas tray bake (Iyer Express)

**Thu**: puttanesca / broccoli / baked potato (Roddy)

**Fri**: Ethiopian Berbere spinach and green split pea with tomato (me) (Miers)

**Sat**: aubergine tomato bake Iyer Express), celeriac (Ottolenghi) and green beans. (

**Sun**: Ethiopian Berbere spinach and yellow split pea with tomato - like using red lentils

#### 2 Monday 22-01-2024 to Sunday 28-01-2024

**Mon**: Courgette and lentil soup

**Tue**: fried potatoes, cabbage and peas (Iyer Express)

**Wed**: noodle soup with prawns inc pak choi, green beans (Iyer Express)

**Thu**: kidney bean, tomato and red pepper tray bake + roast sprouts + small baked potatoes (Iyer Express)

**Fri**: roast squash, red onion + green salad + za’atar (me) (Ottolenghi Jerusalem)

**Sat**: pearl barley + tomato risotto + broccoli (Ottolenghi Jerusalem)

**Sun**: roast aubergine, chick peas, wild rice, fried onion, chopped lemon, peas (Ottolenghi Jerusalem mix)

#### 3 Monday 29-01-2024 to Sunday 04-02-2024

**Mon**: roast squash, red onion + tahini with rice and chick peas (\~Ottolenghi Jerusalem)

**Tue**: lentil, potato and spinach dal “dull dal” + green beans

**Wed**: courgette, lentil, cannellini bean soup + dill, parsley , mint, ginger

**Thu**: puttanesca + kidney beans, green beans + baked potato (Roddy)

**Fri**: roast vegetables (red peppers, aubergine, shallots, courgettes, tomatoes) + baked potato

**Sat**: Cod in tomato sauce with capers and olives + roast sprouts + rice (Roddy)

**Sun**: Urad dal + peas + coconut

#### 4 Monday 05-02-2024 to Sunday 11-02-2024

**Mon**: leek, courgette and potato soup

**Tue**: cannellini bean mash, roast red pepper, roast cauliflower

**Wed**: Patatas yahni - potatoes, tomatoes, olive, tomatoes, all spice. (Jones)

**Thu**: turnip + chickpea and mung bean iranian stew in parsley, coriander

**Fri**: Red fish curry w tomatoes, coconut + broccoli + rice

**Sat**: Caponata (Roddy) = aubergines, tomatoes, olives

**Sun**: Potato, chickpea, courgette, thyme and bay (Roddy)

#### 5 Monday 12-02-2024 to Sunday 18-02-2024

**Mon**: Chicken + sauerkraut (at mum’s)

**Tue**: Patatas yahni - potatoes, tomatoes, olive, tomatoes, all spice. (Jones)

**Wed**: Raie aux câpres + lettuce

**Thu**: Salmon + chips (still at mum’s) + lentil soup

**Fri**: Sicilian lentil soup (roddy, Two Kitchens)

**Sat**: Potato, chickpea, courgette, thyme and bay soup (Roddy)

**Sun**: Roast squash, cauliflower, green beans

#### 6 Monday 19-02-2024 to Sunday 25-02-2024

**Mon**: brown lentil, celery, tomato, carrot onion soup + pasta

**Tue**: Puttanesca + broccoli

**Wed**: Roast vegetables + baked potato

**Thu**: Chickpeas, spinach and tamarind (Iyer)

**Fri**: tomato, onion, olives, capers (Roddy) + sea bass + potatoes

**Sat**: Ethiopian Berbere spinach and green split pea with tomato (Miers) - only soaked peas for one hour. Needed a good hour of cooking.

**Sun**: Romesco + leeks + cannellini + black beans + flat breads (Sodha)

#### 7 Monday 26-02-2024 to Sunday 03-03-2024

**Mon**: Mushrooms with pearl barley + broccoli (Slater) 4

**Tue**: Roast squash, red pepper, cannelloni bean mash, green beans, tahini. 6

**Wed**: Noodle soup w shrimps, red peppers, ginger, garlic, purple sprouting broccoli, rice noodles. 2

**Thu**: Langarwali dal (black urad dal, tomatoes, ginger, coconut) + steamed pak choi (Gowardhan) 4

**Fri**: chicken tagine + asparagus + potato (Mike and Rosy) 1

**Sat**: Minestrone (Roddy) courgette; chard; celery, carrot, onion, cabbage 3

**Sun**: red Lentils + sweet potato + peas + onion + Ras el hanout + coconut + roast squash and beetroot 3.25

***Snacks***: avocado; lime 2.\
**Drinks**: coffee, turmeric tea 2.\
**Breakfast**: nuts (cashew, almond, walnut) **Fruit**: blueberries, pomegranate, raspberry, red currant; oats 8.\
**Lunches**: red onion, carrot, sauerkraut, parsnip, sweet potato, celeriac, coriander, parsley, banana 6.

#### 8 Monday 04-03-2024 to Sunday 10-03-2024

**Mon**: kidney bean, tomato, shallot and red pepper tray bake + roast sprouts + quinoa (Iyer Express)

**Tue**: courgette, pea, lentil soup,.w onion, garlic, thyme, mint

**Wed**: Patatas yahni - potatoes, olive, tomatoes, all spice. (Jones) + broccoli

**Thu**: roast aubergine + tamarind, lentils + tahini + almonds + crispy onions + green beans

**Fri**: Coconut white fish curry + broccoli + quinoa (Sodha)

**Sat**: dull dal with spinach + potatoes + Ras el hanout

**Sun**: Roast squash, cannellini bean mash, red onion, red pepper.

**Drinks**: coffee, turmeric tea 2.\
**Breakfast**: nuts (cashew, almond, walnut, Brazil) **Fruit**: blueberries, pomegranate, raspberry, red currant; oats \
**Lunches**: parsnip, sweet potato, tofu, sauerkraut, brown lentils, coriander, parsley, banana, beetroot.

#### 9 Monday 11-03-2024 to Sunday 17-03-2024

**Mon**: sweet potato, pea, kale, lentil soup,.w onion, garlic, mint

**Tue**: Roast celeriac, cauliflower, red pepper + cannellini bean mash.

**Wed**: Langarwali dal (black urad dal, tomatoes, ginger, coconut) + chapatis (soda)

**Thu**: Patates yahni - potatoes, olive, tomatoes, all spice. (Jones) + broccoli

**Fri**: Vegetable madras + aloo gobi + rice (Maharajah)

**Sat**: Mango, aubergine + soba noodles

**Sun**: Chickpea and red pepper tray bake + green beans (Iyer Express) + flat breads

**Drinks**: coffee, turmeric tea 2.\
**Breakfast**: nuts (cashew, almond, walnut, hazel) **Fruit**: blueberries, pomegranate; oats \
**Lunches**: red onion, parsnip, tofu, sauerkraut, coriander, parsley, banana, carrot, green salad leaves.

#### 10 Monday 18-03-2024 to Sunday 24-03-2024

**Mon**: pearl barley + celery + carrot + onion (HFW)

**Tue**: aloo gobi + flat breads (Cloake)

**Wed**: Pasta e fagioli

**Thu**: roast squash, celeriac, peppers, shallots

**Fri**: sea bass + chips + broccoli

**Sat**: udon vegetable noodle soup, pak choi, courgette, red, green peppers, edamame + black beans

**Sun**: split peas + black beans + roast squash + tomatoes + ras el hanout stew

**Drinks**: coffee, turmeric tea 2.\
**Breakfast**: nuts (cashew, almond, walnut, hazel) **Fruit**: blueberries, pomegranate; oats \
**Lunches**: red onion, parsnip, sweet potato, swede, tofu, sauerkraut, coriander, basil, banana, carrot, green salad leaves, mung dal, garlic, coconut.

#### 11 Monday 25-03-2024 to Sunday 31-03-2024

**Mon**: soup: leek + courgette + onion + potato + basil + parsley

**Tue**: cannellini beans + red onion + roast peppers + toast

**Wed**: Chettiar aubergine curry + coconut + purple sprouting broccoli (Kochhar)

**Thu**: pearl barley + leek + celery + carrot + onion (HFW)

**Fri**: Salmon, peas, green beans, potatoes. 

**Sat**: Ethiopian split pea, tomato and spinach + berbere (Miers)

**Sun**: Patates yahni with  sweet potato + cabbage

**Drinks**: coffee, turmeric tea 2.\
**Breakfast**: nuts (cashew, almond, walnut, hazel, Brazil) **Fruit**: blueberries, oats \
**Lunches**: black beans, celeriac, parsnip, sweet potato, swede, parsley, mixed beans.

#### 12 Monday 01-04-2024 to Sunday 07-04-2024

**Mon**: Miso rice, peas, ginger and mint + roast red peppers (Sodha)

**Tue**: Miso courgette soup + red lentils

**Wed**: Red pepper + chick peas + broccoli

**Thu**: tofu, kala chana, beetroot, sauerkraut

**Fri**: Langarwali dal: black urad dal, tomatoes, ginger, cumin, chilli, coriander (Gowardhan)

**Sat**: Patates yahni + green beans

**Sun**: Roast squash, pinto bean mash, read and green peppers, shallots.

**Drinks**: coffee, turmeric tea 2.\
**Breakfast**: nuts (cashew, almond, walnut, hazel, Brazil) **Fruit**: blueberries, oats \
**Lunches**: pinto beans, kidney beans, parsnip, sweet potato, swede, coriander.

#### 13 Monday 08-04-2024 to Sunday 14-04-2024

**Mon**:Puttanesca + broccoli

Tue**:** Ethiopian split pea, tomato and spinach + berbere (Miers)

**Wed**: Pasta e fagioli (Fish finger sandwich for lunch!)

**Thu**: Mackerel + potato + avocado + spring onion

**Fri**: Noodle soup + prawns + pak choi, shallots, red pepper, ginger, garlic, chilli, miso, spring onion

**Sat**: Pearl barley broth + carrot, celery, tomato + vegetable stock

**Sun**: RRatatouille (green beans, onion, shallot, squash, potato, aubergine, courgette, red pepper, orange pepper, garlic, tomato) (Ottolenghi)

**Drinks**: coffee, turmeric tea, peppermint tea.\
**Spices**: chilli, garlic, berbere, mace, nutmeg, cayenne.\
**Herbs**: coriander, bay, \
**Breakfast**: nuts (cashew, almond, walnut, hazel, Brazil, ).\
**Fruit**: blueberries, oats \
**Lunches**: pinto beans, parsnip, sweet potato, squash.

#### 14 Monday 15-04-2024 to Sunday 21-04-2024

**Mon**: Noodle soup (ginger, courgette, bean noodles, red pepper, tat choi, spring onion, tofu, chilli, broccoli)

**Tue**: Miso rice with ginger, peas, mint + broccoli (Soda)

**Wed**: Rasam + turmeric potato + sea bass + leek + tomato

**Thu**: Green lentil ragu inc onion, mushroom, porcini mushrooms, celery, carrot + purple sprouting broccoli + potato

**Fri**:  Green lentil ragu inc onion, mushroom, porcini mushrooms, celery, carrot + lemon + red chilli + pak choi

**Sat**: Puttanesca pizza (Hazan)

**Sun**: Ethiopian split pea, tomato and spinach + berbere (Miers)

**Drinks**: coffee, turmeric tea, peppermint tea.\
**Spices**: chilli, garlic, tamarind, turmeric, cumin.\
**Herbs**: coriander, bay, thyme, parsley.\
**Fruit**: blueberries, oats \
**Breakfast**: nuts (cashew, almond, walnut, hazel, Brazil, )\
**Lunches**: cannellini beans, parsnip, squash, edamame beans, celeriac.

#### 15 Monday 22-04-2024 to Sunday 28-04-2024

**Mon**:  Baked potato + roast pepper (R&Y), courgette, red onion, tomato, aubergine, garlic

**Tue**: White urad dal + Ras el hanout + ginger + pak choi + leek + lemon + parsley

**Wed**: Miso spring vegetable broth + soba noodles (Slater)

**Thu**: white fish + tomato + coconut curry (Sodha)

**Fri**: vegetable soup (Debs)

**Sat**: Patates yahni (Jones)

**Sun**: Minestroni (inc. chard, carrot, garlic, bay, cannellini bean) \~ pasta e fagioli

**Drinks**: coffee, turmeric tea, peppermint tea.\
**Spices**: red chilli, garlic, turmeric, ginger, ras el hanout, green chilli, smoked paprika, onion seeds, all spice.\
**Herbs**: coriander, parsley, bay, mint, curry leaf, oregano.\
**Vegetables**: onion, red onion, leek, pak choi, courgette, aubergine, tomato, parsnip, celeriac, red pepper, yellow pepper, carrot, lime, chard,  peas, mushrooms, lemon, sweet potato, green beans, broccoli, peas, celery, olives, potato.\
**Pulses / grains**: black beans, kidney beans, oats, haricot beans, urad dal, red lentils.\
**Nuts**: cashew, almond, walnut, Brazil.\
**Fruit**: blueberries, banana.\
**Other**:sauerkraut, tofu, miso.

Veg Stock x1

#### 16 Monday 29-04-2024 to Sunday 05-05-2024

**Mon**: Romesco + leeks + cannellini + black beans + quinoa (Sodha)

**Tue**: Puttanesca + broccoli + spaghetti

**Wed**: Miso rice, peas, ginger and mint + roast red peppers (Sodha)

**Thu**: Salmon + onions, miso, peas, pak choi +lemon

**Fri**: Langarwali dal (black urad dal, tomatoes, ginger) + broccoli (Gowardhan)

**Sat**: dull dal : red lentils, spinach, potato, lemon, ras el hanout

**Sun**: Ratatouille (Ottolenghi)

**Drinks**: coffee, turmeric tea, peppermint tea.\
**Spices**: chilli, sweet paprika, ginger, asafoetida, turmeric, cumin.\
**Herbs**: parsley, mint, basil, coriander.\
**Vegetables**: onion, tomato, garlic, capers, olives, leeks, celeriac, sweet potato, carrot, parsnip, broccoli, red pepper, peas, avocado, lemon, spinach, aubergine, green beans, squash, pak choi, lime.\
**Pulses / grains**: black beans, cannellini beans, pinto beans, quinoa, urad dal.\
**Nuts**: almond, Brazil, walnut.\
**Fruit**: blueberry, banana.\
**Other**: sauerkraut, tofu, miso.

#### 17 Monday 06-05-2024 to Sunday 12-05-2024

**Mon**:  Minestrone (Roddy) + pasta 

**Tue**:  Minestrone (again!)

**Wed**: Roast aubergine, pea and haddock kedgeree (Ray)

**Thu**: Noodle soup + mussels, prawns

**Fri**: Picnic: avocado, hummus, vegan pastie (1/2) 

**Sat**: Mushroom and brown lentil ragu + mashed potato + green beans

**Sun**: Pasta + courgette + edamame beans + basil (Ottolenghi)

**Drinks**: coffee, peppermint tea, turmeric tea.\
**Spices**: smoked paprika, cumin, coriander, ginger, turmeric.\
**Herbs**: bay, sage, chives, parsley, coriander, thyme.\
**Vegetables**: avocado, lime, cabbage, courgette, onion, potato, tomato, celery, carrot, celeriac, sweet potato, parsnip, pea, aubergine, broccoli, red pepper, yellow pepper, mushroom, green pepper, shiitake mushroom.\
**Pulses / grains**: cannellini beans, borlotti beans, mung dal, basmati rice, brown lentil, green lentil.\
**Nuts**: walnut, Brazil, almond.\
**Fruit**: blueberry, raspberry, strawberry, raisin, banana.\
**Other**: Vegetable stock, tofu, sauerkraut, miso.

#### 18 Monday 13-05-2024 to Sunday 19-05-2024

**Mon**: Courgette soup (+ various veg) + flatbreads

**Tue**: Chickpea and red pepper tray bake + broccoli (Iyer Express)

**Wed**: Ethiopian Berbere spinach and red lentil with tomato (me) (Miers)

**Thu**: Miso vegetable broth (Slater)

**Fri**: seafood pizza (Secret Garden,Newquay)

**Sat**: mushroom soup (breakfast), miso vegetable broth

**Sun**: Gujarati dal (Gowardhan)

**Drinks**: coffee, peppermint tea, turmeric tea.\
**Spices**: cumin, turmeric, coriander, ginger, berbere mix, green chilli, thyme, tamarind,asafoetida, curry leaves, mustard seeds.\
**Herbs**: basil, coriander, parsley, mint.\
**Vegetables**: avocado, squash, onion, sweet potato, courgette, celeriac, parsnip, red pepper, tomato, red onion, broccoli, spinach, potato, lime, carrot, mushroom, pak choi, peas, fennel.\
**Pulses / grains**: red lentils, edamame beans, chick pea, butter beans, kala chick pea, oats, haricot beans, toor dal.\
**Nuts**: almond, Brazil, walnut.\
**Fruit**: blueberry, banana, raspberry.\
**Other**: miso, tofu, sauerkraut.

#### 19 Monday 20-05-2024 to Sunday 26-05-2024

**Mon**: Pasta e fagioli (Roddy)

**Tue**: Miso & maple-glazed aubergine, roast red peppers, black beans

**Wed**: Mushroom and brown lentil ragu + mashed potato + green beans

**Thu**: Courgette, cannellini bean, rosemary stew (Roddy)

**Fri**: Spiced tomato + cod stew (Roddy), potatoes, broccoli, mezze inc. baba ganoush, labneh, glazed carrots (Roden) - Mike and Rosy

**Sat** Minestrone (Roddy)

**Sun** Prawns + harissa (Moro), broccoli stems, green beans, salad leaves

**Drinks**: coffee, turmeric tea, peppermint tea.\
**Spices**: chilli, harissa.\
**Herbs**: coriander, basil, parsley, rosemary, sage.\
**Vegetables**: celeriac, sweet potato, tomato, red onion, aubergine, red pepper, parsnip, green beans, mushrooms, olives, courgette, celery, garlic, broccoli, tahini, carrot, swede.\
**Pulses / grains**: borlotti beans, oats, cannellini beans, black beans, brown lentils.\
**Nuts**: walnut, almond, brazil.\
**Fruit**: rhubarb, blueberries, raspberries, pomegranate, strawberries.\
**Other**: tofu, sauerkraut, miso, vegetable stock.

#### 20 Monday 27-05-2024 to Sunday 02-06-2024

**Mon**: Pasta + courgette + edamame beans + basil (Ottolenghi).

**Tue**: Mango, aubergine, soba noodles

**Wed**: Caponata: aubergines, tomatoes, olives, capers,basil, red onion (Roddy).

**Thu**: Miso rice, peas, ginger and mint + roast red peppers (Sodha).

**Fri**: Brown lentil, yellow courgette, cavolo nero soup (Roddy-ish)

**Sat**: Coconut white fish curry + broccoli + brown rice (Sodha)

**Sun**: Stuffed tomato, roast carrot, celeriac, sweet potato, pinto + borlotti bean hummus.

**Drinks**: coffee, peppermint tea, turmeric tea.\
**Spices**: red chilli, ginger, green chilli\
**Herbs**: basil, flat-leaf parsley, rosemary, mint, bay, curry leaves,\
**Vegetables**: avocado, courgette, red onion, lemon zest, lime, aubergine, tomato, caper, olive, garlic, shallot, spring onion, red pepper, yellow pepper, peas, sweet potato, swede, carrot, potato, yellow courgette, cavolo nero, celeriac.\
**Pulses / grains**: oats, chick peas, edamame beans, cannellini beans, brown lentils, pinto beans, borlotti beans.\
**Nuts**: almond, walnut, brazil.\
**Fruit**: pomegranate, blueberry, strawberry, raspberry, mango, banana.\
**Other**: sauerkraut, tofu, miso, vegetable stock.

#### 21 Monday 03-06-2024 to Sunday 09-06-2024

**Mon**: Patates yahni (olives, potato, tomato) (Jones)

**Tue**: Miso vegetable broth (Slater)

**Wed**: Sea bass, peas, chips

**Thu**: cannellini bean, courgette and cocunut curry (sodha)

**Fri**: Vegetable barbecue (camping)

**Sat**: Vegetable barbecue (camping)

**Sun**: Simple dal

**Drinks**: coffee, peppermint tea, turmeric tea.\
**Spices**: all spice, chilli, turmeric\
**Herbs**: coriander, basil.\
**Vegetables**: swede, sweet potato, celeriac, carrot, potato, olives, tomato, garlic, cucumber, onion, red onion, asparagus, peas, pak choi, cabbage, courgette, mushrooms, red pepper, yellow pepper, aubergine, avocado.\
**Pulses / grains**: pinto beans, borlotti beans, cannellini beans, puy lentils, red lentils\
**Nuts**: sunflower seeds, pumpkin seeds, walnut.\
**Fruit**: blueberry, banana, strawberry, raspberry. **Other**: sauerkraut, tofu, miso, vegetable stock.

#### 22 Monday 10-06-2024 to Sunday 16-06-2024

**Mon**: Roasted sweet corn, red and yellow peppers, baked potato

**Tue**: Courgette, cannellini bean, rosemary soup (Roddy)

**Wed**: Grilled mackerel, brown rice + onion + courgette + capers + black beans, + broccoli

**Thu**: Harira chick pea and squash stew

**Fri**: Pasta a la Norma + bucatini + runner beans

**Sat**: Noodle soup + pak choi, mushrooms, ginger, miso

**Sun**: Sea bass + chips + peas

**Drinks**: coffee, peppermint tea, turmeric tea.\
**Spices**: cinnamon, turmeric, saffron, chilli, tamarind, coriander, fenugreek, cumin, ginger\
**Herbs**: rosemary, fennel, coriander, parsley, mint, oregano **Vegetables**: corn, red pepper, yellow pepper, salad leaves, courgette, potato, celeriac, parsnip, capers, broccoli, chicory, rocket, runner beans, aubergine, spring onions, pak choi\
**Pulses / grains**: pinto beans, cannellini beans, black beans, kidney beans, chick peas, toor dal\
**Nuts**: brazil, walnut.\
**Fruit**: blueberry, banana, strawberry, raspberry\
**Other**: sauerkraut, tofu, vegetable stock, miso

#### 23 Monday 17-06-2024 to Sunday 23-06-2024

**Mon**: grilled red pepper, corn, flageolet beans + steamed potatoes

**Tue**: Pasta + courgette + edamame beans + basil + mozarella (Ottolenghi)

**Wed**: Courgette and lentil soup

**Thu**: Baked potato, roast peppers, corn, green salad

**Fri**: Stuffed courgette, parsley, beetroot leaves, anchovy

**Sat**: Vegan wedding buffet, chick pea salad, pasty

**Sun**: Stuffed tomato, grilled halloumi, grilled lettuce, pasta

**Drinks**: coffee, peppermint tea, turmeric tea.\
**Spices**: smoked paprika, all spice\
**Herbs**: parsley, purslane, mint, basil,\
**Vegetables**: pak choi, red onion, red pepper, corn, tomato, squash, lemon, courgette, beetroot leaves, onion, celery, celeriac\
**Pulses / grains**: flageolet beans, black eyed beans, edamame beans, red lentils, chick peas, cannellini beans\
**Nuts**: brazil, almond, walnut\
**Fruit**:banana, peach\
**Other**: tofu

#### 24 Monday 24-06-2024 to Sunday 30-06-2024

**Mon**: Langarwali dal: black urad dal, tomatoes, ginger, chilli, coriander (Gowardhan)

**Tue**: Courgette, cannellini bean, rosemary soup (Roddy)

**Wed**: Aubergine stuffed with onion, olive, tomato, basil and halloumi + potatoes + green beans

**Thu**: Prawns in harissa sauce, grilled padron peppers + lettuce, mung bean noodles, steamed pak choi

**Fri**: Chickpea, anchovy + sofrito + pasta soup (Roddy)

**Sat**: 'dull' dal = red lentils, potato, spinach, pak choi, ras-el-hanout + lemon

**Sun**: Salmon, chips and peas

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: chilli, garam masala, ginger, turmeric, harissa, ras el hanout\
**Herbs**: parsley, purslane, beetroot leaves, coriander, rosemary, basil, rocket, bay\
**Vegetables**: celeriac, parsnip, pak choi, onion, tomato, courgette, garlic, celery, aubergine, olives, green beans, padron peppers, lettuce, lemon, avocado, carrot\
**Pulses / grains**: black urad dal, cannellini beans, mung bean noodles, chick peas, red lentils\
**Nuts**: walnut, brazil, almond\
**Fruit**: banana, peach\
**Other**: vegetable stock, sauerkraut, tofu

#### 25 Monday 01-07-2024 to Sunday 08-07-2024

**Mon**: Black bean salad, roast red peppers, tomatoes, baked potato

**Tue**: Puttanesca + cannellini beans + rocket

**Wed**: Courgette soup

**Thu**: Roast tomato, garlic and aubergine, butter bean, cashew + smoked tofu dip + flatbreads (Mansell)

**Fri**: Stuffed tomatoes, aubergine, pinto beans, olives

**Sat**: padrons, peppers, pak choi, prawns in harissa, steamed new potatoes

**Sun**: Pasta + courgette + edamame beans + basil (Ottolenghi) + pak choi

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: cayenne\
**Herbs**: parsley, basil, rocket, oregano, mint\
**Vegetables**: celeriac, parsnip, red onion, capers, olives, shallot, tomato, carrot, courgette, green beans, onion, garlic, lemon, padrons, pak choi, red pepper, yellow pepper\
**Pulses / grains**: black beans, cannellini beans, butter beans, pinto beans, red lentil, black eyed beans\
**Nuts**: walnut, brazil, almond, cashew\
**Fruit**: blueberries, blackcurrants,\
**Other**: sauerkraut, tofu

#### 26 Monday 08-07-2024 to Sunday 14-07-2024

**Mon**: pasta e fagioli with toor dal

**Tue**: grilled sea bass, padrons, yellow pepper, steamed pak choi

**Wed**: hake, mushrooms, padrons, red pepper, steamed pak choi, basil

**Thu**: pasta a la Norma + green beans

**Fri**: courgette, pak choi, parley and basil soup

**Sat**: whiting, carrot and mash (Cafe du Port)

**Sun**: Fish pies (mum)

**Drinks**: coffee peppermint tea, turmeric tea\
**Spices**: pepper flakes\
**Herbs**: parsley, sage, basil, bay, oregano\
**Vegetables**: onion, celery, garlic, tomato, pak choi, yellow pepper, padron pepper, parsnip, carrot, red onion, red pepper, mushroom, broccoli, green beans, courgette, aubergine\
**Pulses / grains**: black eyed beans, toor dal, oats, borlotti beans, black beans\
**Nuts**: cashew, brazil, walnut\
**Fruit**: blueberry, pomegranate, peach\
**Other**: sauerkraut, tofu, miso

#### 27 Monday 15-07-2024 to Sunday 21-07-2024

**Mon**: vegetable soup, cannellini beans, tomato

**Tue**: sardines, cannellini beans, tomato

**Wed**: tuna, cannellini beans, tomato

**Thu**: Green salad, feta, melon, kidney beans, peach

**Fri**:

**Sat**:

**Sun**:

**Drinks**: coffee, turmeric tea\
**Spices**:\
**Herbs**:\
**Vegetables**: tomato, lettuce\
**Pulses / grains**: cannellini beans\
**Nuts**: walnut, sunflower seed\
**Fruit**: apple\
**Other**:

\*\*\*\* SUMMER BREAK \*\*\*\*

#### 28 Monday 12-08-2024 to Sunday 18-08-2024

**Mon**: courgette, chick pea, potato soup (Roddy)

**Tue**: Tomato soup (Cloake) our tomatoes, basil

**Wed**: Pasta a la Norma (our tomatoes,aubergines)

**Thu**: mixed salad - green lentils, smoked salmon, beetroot, red onion, french beans, tomato, walnuts, goats cheese

**Fri**: Indian meal out: dansek vegetable, saag aloo

**Sat**: Allotment barbecue: beetroot, walnut, red onion, goat's cheese salad

**Sun**: Pasta + courgette + edamame beans + basil (Ottolenghi).

**Drinks**: coffee, turmeric tea, peppermint tea\
**Spices**: chilli\
**Herbs**: rosemary, basil, parsley, oregano, sage\
**Vegetables**: tomato, yellow tomato, potato, red onion, onion, courgette, spring onion, parsnip, beetroot, carrot, aubergine, french beans, capers\
**Pulses / grains**: chick peas, butter beans, cannellini beans, green lentils, edameme beans\
**Nuts**: brazil, cashew, almond, walnut\
**Fruit**: blueberry, rhubarb, strawberry\
**Other**: vegetable stock x 2, sauerkraut

#### 29 Monday 19-08-2024 to Sunday 25-08-2024

**Mon**: Cod in tomato sauce with capers and olives (Roddy)

**Tue**: Pinto bean, yellow squash, potato soup

**Wed**: grilled padrons, corn, sea bass.

**Thu**: aubergine, coconut, tomato, potato curry (Kochhar)

**Fri**: courgette soup, aubergine + tomato

**Sat**: grilled padrons, mushroooms, tomato, aubergine

**Sun**: grilled aubergine, tomato, red onion, courgette, mushroom, cannellini beans

**Drinks**: coffee, turmeric tea\
**Spices**: chilli, sumac\
**Herbs**: rosemary, parsley, basil\
**Vegetables**: tomato, yellow tomato, potato, onion, beetroot, french beans, capers, yellow courgette, yellow squash, olives, mushrooms, corn cob, coconut, aubergine, broccoli, asparagus, padron peppers\
**Pulses / grains** puy lentils, pinto beans, black beans, black eyed beans, cannellini beans\
**Nuts**: walnut, almond, cashew, brazil\
**Fruit**: blueberry, rhubarb, strawberry, pomegranate\
**Other**: sauerkraut, tofu

#### 30 Monday 26-08-2024 to Sunday 01-09-2024

**Mon**: aubergines, chick peas, tomato, peppers (Falastin) + baked potato

**Tue**: puttanesca, broccoli stems, buccatini

**Wed**: tomato soup (Cloake)

**Thu**: dull dal = red lentil, spinach, potato, lemon, ras el hanout

**Fri**: Grilled sea bass, red pepper, aubergine, yellow courgette + potato

**Sat**: Grilled sea bass, red pepper, aubergine, yellow courgette + potato

**Sun**: Pasta a la Nprma + mozzarella (Roddy)

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: cumin, chilli, ras el hanout, turmeric\
**Herbs**: basil, parsley\
**Vegetables**: tomato, yellow tomatos, aubergine, onion, potato, red onion, yellow pepper, green pepper, red pepper, garlic, broccoli, caper, black olive, green olive, beetroot, spinach, cabbage, yellow courgette, lemon\
**Pulses / grains**: chick pea, cannellini beans, black beans, red lentils, kidney beans\
**Nuts**: brazil, cashew, almond, walnut\
**Fruit**: pomegranate, blueberry, rhubarb, strawberry, banana, figs **Other**: sauerkraut, tofu

#### 31 Monday 02-09-2024 to Sunday 08-09-2024

**Mon**: rainbow chard sag aloo + coconut

**Tue**: courgette, lentil soup

**Wed**: puttanesca + broccoli + baked poato

**Thu**: cannellini bean homous, chick peas, tomatoes, noodles, mint, basil, aubergine

**Fri**: yellow courgette, lentil soup

**Sat**: Beetroot salad

**Sun**: Sea bass, potato salad, roast peppers and aubergines (campsite)

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: mustard seeds, ginger, cumin, coriander, chilli, turmeric, zaatar\
**Herbs**: mint, basil, parsley\
**Vegetables**: rainbow chard, potato, red tomato, yellow tomato, onion, yellow courgette, courgette, garlic, red onion, aubergine, celeriac, sweet potato, beetroot, spring onion, yellow pepper, red pepper\
**Pulses / grains**: kidney beans, red lentil, pinto beans, cannellini beans, chick peas\
**Nuts**: cashew, walnut, brazil, almond, pumpkin seed\
**Fruit**: blueberry, pomegranate, banana\
**Other**: sauerkrauet, tofu

#### 32 Monday 09-09-2024 to Sunday 15-09-2024

**Mon**: pearl barley broth

**Tue**: udon noodle soup, broccoli, pak choi, prawns

**Wed**: chick pea, courgette, potato soup (Roddy)

**Thu**: chick pea, courgette, potato soup (Roddy) - the rest

**Fri**: Hake in tomato sauce with capers and olives + sweet potoato (Roddy).

**Sat**: beetroot, lentil salad + veg quiche at John Lewis

**Sun**: Chettiar aubergine curry (Kochhar)

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: mace, chilli powder, nutmeg, ginger, coriander seeds, fennel\
**Herbs**: sage, dill, thyme, bay, rosemary, parsley, curry leaves\
**Vegetables**: sweet potato, potato, parsnip, carrot, yellow tomato, red tomato yellow pepper, red pepper, aubergine, pak choi, peas, broccoli, mushroom, garlic, courgette, yellow round courgette, onion, red onion, olive, caper, coconut milk\
**Pulses / grains**: borlotti beans, pearl barley, edamame beans, chick peas, black beans, oats, green lentils\
**Nuts**: cashew, walnut, almond, brazil\
**Fruit**: banana, fig, peach\
**Other**: vegetable stock, sauerkraut, tofu, miso paste

#### 33 Monday 16-09-2024 to Sunday 22-09-2024

**Mon**: Marrow + potato soup

**Tue**: Miso rice, peas, ginger and mint + roast cauliflower (Sodha)

**Wed**: Marrow soup + cannellini beans

**Thu**: Puy lentil, + carrot, roasted pepper, aubergines.

**Fri**: Sri Lankan fish curry + green beamns, basmati rice (Kolamba)

**Sat**: Courgette, pinto bean, tomato curry + baked potato (Sodha)

**Sun**: Griled sea bass (caught by Mark), puttanesca, mashed potato

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: turmeric,cumin, ginger, coriander, fenugreek, cinnamon, mustard seeds, fennel seeds, mustard seeds, rosemary\
**Herbs**: dill, mint, basil, parsley, curry leaves\
**Vegetables**: red onion, yellow tomato, red tomato, parsnip, carrot, sweet potato, olives, beetroot, green pepper, marrow, yellow pepper, cauliflower, peas, onion, red pepper, green beans, yellow courgette, capers\
**Pulses / grains**: oats, black beans, puy lentils, chick peas, cannellini beans\
**Nuts**: walnut, brazil, almond, cashew, sesame seeds\
**Fruit**: blueberries, fig, banana, peach, russet apple\
**Other**: sauerkraut, tofu, vegetable stock, miso

#### 34 Monday 23-09-2024 to Sunday 29-09-2024

**Mon**: Tomato soup (Cloake)

**Tue**: Chips! (Headland Hotel)

**Wed**: Pasta a la Norma

**Thu**: dull dal (red lentils, spinach, potatoes, lemon)

**Fri**: Viraj! Aloo gobi + vegetabe biryani

**Sat**: Viraj reamins. Chard, butter beans, leek and coconut

**Sun**: Ethiopian Berbere spinach, pak choi and yellow split pea with tomato (Miers).

**Drinks**: coffee, turmeric tea, peppermint tea\
**Spices**: harissa, ras el hanout, baharat, coconut, cumin, coriander, berbere **Herbs**: parsley, basil\
**Vegetables**: yellow pepper, beetroot, sweet potato, parsnip, tomato, yellow tomato, capers, olives, red onion, onion, garlic, orange pepper, aubergine, broccoli, spinach, lemon, red pepper, spring onion, cucumber, rocket, chard, pak choi, green chilli\
**Pulses / grains**: borlotti beans, green lentils, red lentils, butter beans, black beans, yellow split pea\
**Nuts**: cashew, almond, brazil, walnut\
**Fruit**: fig, peach, banana, russet apple, pomegranate\
**Other**: sauerkraut, harissa, tofu

#### 35 Monday 30-09-2024 to Sunday 06-10-2024

**Mon**: roast squash, aubergines, steamed kale + chilli and garlic

**Tue**: roast squash, aubergines, broccoli, flageolet beans

**Wed**: Patates yahni (Jones) + green beans

**Thu**: Courgette, cannellini bean, potato, rosemary soup (Roddy)

**Fri**: home made chips (few), sweet corn, broccoli

**Sat**: dal, leeks (from allotment), coconut (similar to Langarwali dal)

**Sun**: Basa in tomato sauce with capers and olives + urad dal (Roddy)

**Drinks**: coffee, turmeric tea, peppermint tea\
**Spices**: chilli, harissa, all spice, cumin, coriander, asafoetida, turmeric\
**Herbs**: parsley, sage, rosemary\
**Vegetables**: squash, kale, red onion, chilli, garlic, lemon, aubergine, broccoli, parsnip, beetroot, French beans, olives, tomato, yellow tomato, yellow pepper, onion, yellow courgette, carrot, rocket, red pepper, green courgette, mushroom,sweet corn, leek, ginger\
**Pulses / grains**: black beans, flageolet beans, cannellini beans, red lentils, urad dal\
**Nuts**: almond, walnut, brazil, cashew\
**Fruit**: apple, redcurrant, peach\
**Other**: sauerkraut, tofu

#### 36 Monday 07-10-2024 to Sunday 13-10-2024

**Mon**: baked potato, tomatoes, sardines, green beans

**Tue**: courgette soup with potato and leek + vegetable stock

**Wed**: Roast squash, borlotti beans, tomato, roast aubergine

**Thu**: pasta e fagioli wih leek and borlotti beans

**Fri**: dull dal: red lentil, potato, spinach, ras el hanout

**Sat**: Romesco + leeks + cannellini + black beans + toast (Sodha).

**Sun**: Chettiar aubergine curry (Kochhar)

**Drinks**: coffee, turmeric tea, peppermint tea\
**Spices**: chilli\
**Herbs**: parsley, sage, bay\
**Vegetables**: avocado, green beans, red onion, red pepper, olive, red tomato, lime, leek, courgette, lemon, yellow pepper, squash, garlic, yellow tomato, spinach,aubergine\
**Pulses / grains**: urad dal, oats, borlotti beans, red lentil, kidney beans, cannellini beans, black beans\
**Nuts**: brazil, cashew, walnut, almond\
**Fruit**: peach, banana, blueberry, pomegranate, fig, apricot\
**Other**: sauerkraut, tofu, vegetable stock, coconut milk

#### 37 Monday 14-10-2024 to Sunday 20-10-2024

**Mon**: roast squash, red pepper, red onion, aubergine

**Tue**: lentil, squash, aubergine, shallot, peas dunbas (Sodha)

**Wed**: Three bean stew + potato + rosemary and sage (Roddy)

**Thu**: leek, potato, courgette soup

**Fri**: brown lentil ragu lasagne + broccoli (Ottolenghi)

**Sat**: chard, potato, peas, coconut (Sodha)

**Sun**: Ratatouille (Ottolenghi)

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: chilli, mustard seed, tamarind, fenugreek, cumin, coriander, turmeric\
**Herbs**: sampan, curry leaf, parsley, rosemary, sage, basil **Vegetables**: squash, red onion, aubergine, red pepper, olive, red tomato, yellow tomato, sweet potato, beetroot, parsnip, green pepper, yellow pepper, green salad leaves, shallot, peas, garlic, parsnip, carrot, coconut, courgette, green beans, broccoli, mushroom, chard\
**Pulses / grains**: borlotti beans, oats, red lentils, cannellini beans, pinto beans, chick peas, brown lentils, pearl barley\
**Nuts**: walnut, almond, brazil, cashew\
**Fruit**: fig, apricot, banana, raspberry, blueberry\
**Other**: sauerkraut, tofu.

#### 38 Monday 21-10-2024 to Sunday 27-10-2024

**Mon**: squash and chick pea stew

**Tue**: brown lentil ragu lasagne + broccoli (Ottolenghi)

**Wed**: Noodle soup + prawns, pak choi

**Thu**: fish finger sandwich + steamed leeks

**Fri**: puttanesca

**Sat**: buillabaisse (Sam's)

**Sun**: courgette soup + tofu , potato salad

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: chilli, coriander, cumin, mustard seeds,\
**Herbs**: parsley, green salad leaf, basil, pandan, curry leaf, salad leaves, chives\
**Vegetables**: green beans, squash, aubergine, courgette, red pepper, orange pepper, garlic, red onion, potato, yellow pepper, sweet potato, squash, broccoli, red tomato, yellow tomato, onion, chard, leek, pak choi, olive, avocado\
**Pulses / grains**: chick pea, kidney beans, black beans, green lentils, red lentils\
**Nuts**: cashew, brazil, almond, walnut\
**Fruit**: banana, blueberry, pomegranate, raspberry\
**Other**: tofu, vegetable stock\

#### 39 Monday 28-10-2024 to Sunday 03-11-2024

**Mon**: Chettiar aubergine curry (Kochhar)

**Tue**: leek and potato soup with courgette

**Wed**: leek and potato soup with carrot

**Thu**: leek and potato soup with courgette

**Fri**: squash, sweet potato and potato soup + roast cauliflower (Sodha)

**Sat**: Patates yahni (Jones)

**Sun**: ragu (Roddy)

**Drinks**: coffee, peppermint tea\
**Spices**: coriander, chilli, cinnamon, fennel, turmeric, cumin\
**Herbs**: chives, parsley, salad leaves\
**Vegetables**: chard, aubergine, yellow tomato, red tomato, leek, potato, red onion, yellow onion, sheep's lettuce, courgette, garlic, chives, orange pepper, lemon, carrot, squash, sweet potato, cauliflower\
**Pulses / grains**: green lentil, flageolet beans, coco de Paimpol, kidney beans\
**Nuts**: brazil, cashew, almond, walnut **Fruit**: banana, apple, fig\
**Other**: tofu, coconut milk, sauerkraut.

#### 40 Monday 04-11-2024 to Sunday 10-11-2024

**Mon**: Ragu (Roddy) + baked potato

**Tue**: Leek and potato soup

**Wed**: salmon, rice and peas

**Thu**: squash, chick pea and orzo (Debs' thing from HFW- not very nice!)

**Fri**: Pasta and chick peas + rosemary soup (Roddy)

**Sat**: Leek, courgette, potato soup

**Sun**: Langarwali dal (Gowardhan)

**Drinks**: turmeric tea, coffee, peppermint tea\
**Spices**: chilli, turmeric, asoefatida, ginger\
**Herbs**: salad leaves, parsley, mint, rosemary\
**Vegetables**: onion, leek, garlic, olive, orange pepper, red tomato, parsnip, red onion, yellow pepper, squash, carrot, celery, sweet potato, peas, lemon, beetroot\
**Pulses / grains**: brown lentils, edamame beans, borlotti beans, chick peas, oats, black urad dal,\
**Nuts**: walnut, brazil, almond, cashew\
**Fruit**: banana, blueberry, pomegranate, apple, raspberry, redcurrant\
**Other**: tofu, sauerkraut, coconut.

#### 41 Monday 11-11-2024 to Sunday 17-11-2024

**Mon**: Langarwali dal (Gowardhan), purple sprouting broccoli

**Tue**: Mushrooms, pearl barley, basil (Slater)

**Wed**: Baked potato, peppers, tofu, kidney beans

**Thu**: cannellini beans, courgette, coconut, ginger (Roddy x Sodha)

**Fri**: cannellini beans, courgette, coconut, ginger (Roddy x Sodha)

**Sat**: Winter minestroni (River Café blue book)

**Sun**: Winter minestroni (River Café blue book)

**Drinks**: peppermint tea, coffee, turmeric tea\
**Spices**: chilli, turmeric, asafoetida, ginger, coconut milk, mustard seeds\
**Herbs**: parsley, salad leaves, basil, curry leaves, sage, bay\
**Vegetables**: pak choi, sweet potato, celeriac, red onion, onion, red tomato, yellow tomato, purple sprouting broccoli, beetroot, mushrooms, green beans, yellow pepper, courgette, leek, celery, chard, spinach, carrot, cauliflower\
**Pulses / grains**: black urad dal, borlotti beans, pearl barley, kidney beans, oats, black beans, cannellini beans\
**Nuts**: almond, walnut, brazil, cashew\
**Fruit**: apple, raspberry, redcurrant, banana, blueberry. pomegranate\
**Other**: tofu, sauerkraut, vegetable stock.

#### 42 Monday 18-11-2024 to Sunday 24-11-2024

**Mon**: Leek and potato soup

**Tue**: roast aubergine, pepper, courgette + green beans

**Wed**: chick peas with cavolo nero (River Cafe Blue p172)

**Thu**: miso rice and peas with mint + seafood (Sodha)

**Fri**: prawn chow mien (take away). Yuk!

**Sat**: split peas, chard, turmeric, onion, parsley, rice, turnip

**Sun**: seafood, peppers, root vegetables, green beans,

**Drinks**: coffee, turmeric tea, peppermint tea\
**Spices**: chilli, ginger, turmeric, cumin, mustard seeds\
**Herbs**: parsley, bay, coriander, rocket, water cress, rosemary, mint,curry leaves, pandan\
**Vegetables**: celeriac, sweet potato, onion, leek, garlic, tomato, olive, spring onion, carrot, celery, potato, aubergine, courgette, green beans, orange pepper, red pepper, parsnip, avocado, spinach, cavolo nero, red onion, lemon, peas, chard, turnip\
**Pulses / grains**: flageolet beans, kidney beans, chick peas, green split peas\
**Nuts**: cashew, brazil, almond, walnut, pecan, pumpkin seeds\
**Fruit**: apple, raspberry, redcurrant, blueberry, banana\
**Other**: sauerkraut, tofu, vegetable stock, miso

#### 43 Monday 25-11-2024 to Sunday 01-12-2024

**Mon**: courgette, leek soup

**Tue**: marguerita pizza, olives, anchovies on sourdough (Hazan)

**Wed**: pasta e fagioli

**Thu**:

**Fri**: sea bass, chips, hunmmus, aubergine dip

**Sat**: prawns, harissa, noodles

**Sun**: lentils e fagioli

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: chilli\
**Herbs**: parsley, spinach, water cress\
**Vegetables**: red pepper, orange pepper, red onion, onion, leek, courgette, parsley, olives, celeriac, sweet potato, garlic\
**Pulses / grains**: borlotti beans, flageolet beans, red lentils, oats, brown lentiles\
**Nuts**: pecan, brazil, cashew\
**Fruit**: raspberry, red currant, apple\
**Other**: tofu, sauerkraut, vegetable stock

#### 44 Monday 02-12-2024 to Sunday 08-12-2024

**Mon**: patates yahni (Jones)

**Tue**: Romescu (red peppers, beans and leeks) + flatbreads (Sodha)

**Wed**: Tarka dal (Sodha)

**Thu**: sweet corn chowder (Sodha) + beans

**Fri**: fish finger sandwiches (Deb's pre-birthday)

**Sat**: carrot and courgette soup

**Sun**: mussels, seafood linguini (Debs birthday meal at The Heron)

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**:\
**Herbs**: parsley\
**Vegetables**: carrot, courgette, red pepper, orange pepper, celeriac, parsnip, sweet potato, onion, red onion, leeks, sweet corn, purple carrot, yellow carrot, olives, tomato\
**Pulses / grains**: mung dal, black beans, cannellini beans, red lentils, oats\
**Nuts**: pecan, cashew, walnut, brazil almond\
**Fruit**: blueberries, banana\
**Other**: sauerkraut, tofu

#### 45 Monday 09-12-2024 to Sunday 15-12-2024

**Mon**: courgette soup

**Tue**: Romescu (sodha), roast cauliflower (Sodha), green beans

**Wed**: Pasta + courgette + edamame beans + basil (Ottolenghi).

**Thu**: Stuffed aubergine + curly kale

**Fri**: Stuffed aubergine + broccoli stems + baked potato

**Sat**: Ethiopian Berbere, spinach and yellow split pea with tomato, potato, chard

**Sun**: Cornish yarg + sweet potato frittata (Boscastle Farm Shop Cafe)

**Drinks**: coffee, peppermint tea, turmeric tea.\
**Spices**: turmeric, cumin, sweet paprika, chilli, all spice, ginger, berbere\
**Herbs**: coriander, basil, bay, sage\
**Vegetables**: courgette, red onion, onion, sweet potato, celeriac, red pepper, orange pepper, olives, tomato, capers, yellow carrot, parsnip, purple carrot, kale, aubergine, broccoli, chard, spinach\
**Pulses / grains**: red lentils, borlotti beans, oats, black beans, cannellini beans, edamame beans, yellow split pea\
**Nuts**: pecan, walnut, brazil, cashew, almond,\
**Fruit**: pomegranate, blueberry, raspberry, banana\
**Other**: tofu, vegetable stock, sauerkraut

#### 46 Monday 16-12-2024 to Sunday 22-12-2024

**Mon**: brown lentil soup + pasta (Roddy)

**Tue**: courgette soup

**Wed**: Coconut white fish curry + broccoli + rice (Sodha).

**Thu**: minestrone (with cannellini beans, chard, aubergine!, courgette)

**Fri**: sea bass + new potatoes + green beans (Steams)

**Sat**: lentil + courgette + squash soup

**Sun**: Various dips from Falastin: hummus, red pepper + walnut, Jerusalem: babaganoush (Debbie's family do)

**Drinks**: coffee, turmeric tea, peppermint tea\
**Spices**: chilli, turmeric, smoked paprika\
**Herbs**: bay, sage, parsley, basil, fennel seeds\
**Vegetables**: red tomatoes, olive, rocket, spinach, parsnip, sweet potato, potato, onion, spring onion, red onion, garlic, courgette, leek, broccoli, aubergine, chard, carrot, red pepper, celeriac\
**Pulses / grains**: borlotti beans, brown lentils, red lentils, oats, kidney beans, cannellini beans\
**Nuts**: pecan, walnut, cashew, brazil\
**Fruit**: fig, blueberries, banana, pomegranate\
**Other**: sauerkraut, tofu, vegetable stock

#### 47 Monday 23-12-2024 to Sunday 29-12-2024

**Mon**: celeriac, sardine, sauerkraut

**Tue**: celeriac, kidney beans, sauerkraut

**Wed**: fish cassoulet, broccoli + Christmas picnic of salmon pittas.

**Thu**: ratatouille, roast sprouts, majedra, roast sweet potato + parsnip, roast cauliflower (Boxing Day - 11 people)

**Fri**: mung bean dal with chard

**Sat**: ribollita with chick peas (River Café blue)

**Sun**: roast cauliflower

**Drinks**: coffee, turmeric tea\
**Spices**: turmeric, all spice, cinnamon, ras el hanout, ginger, chilli, cumin, coriander\
**Herbs**: parsley, rosemary, thyme, coriander\
**Vegetables**: celeriac, sweet potato, parsnip, red pepper, avocado, rocket, spinach, broccoli, sprouts, tomato, onion, celery, aubergine, green beans, courgette, squash, cauliflower, cavolo nero, chard, red onion\
**Pulses / grains**: kidney beans, cannellini beans, brown lentils, mung beans, chick peas\
**Nuts**: walnuts, pecan, brazil, pumpkin seeds, sesame seeds\
**Fruit**: blueberry, banana, pomegranate\
**Other**: sauerkraut, tofu

#### 48 Monday 30-12-2024 to Sunday 05-01-2025

**Mon**: lentil + courgette soup

**Tue**: cocunut braised winter greens (Sodha)

**Wed**: patates yahni (Jones)

**Thu**: Pollock in tomato sauce with capers and olives + baked red cabbage + potatoes (Roddy).

**Fri**: fishfingers + chips + peas + halloumi (for M & W)

**Sat**: fasoulia (Sodha)

**Sun**: grilled mackerel + braised lentils (Roddy)

**Drinks**: coffee, turmeric tea, peppermint tea\
**Spices**: ginger, coriander, chilli, all spice, cinnamon, cumin\
**Herbs**: coriander, parsley, basil, sage, bay\
**Vegetables**: onion, courgette, carrot, celery, lemon, cavolo nero, red cabbage, peas, coconut milk, tomato, olives, parsnip, sweet potato, rocket, orange pepper, spinach, red onion\
**Pulses / grains**: red lentils, borlotti beans, cannellini beans, chick peas, brown lentils\
**Nuts**: walnuts, cashew, pumpkin seeds, brazil, pecan, tahini\
**Fruit**: banana, blueberry, pomegranate, apricot, apple\
**Other**: sauerkraut, miso, tofu

#### 49 Monday 06-01-2025 to Sunday 12-01-2025

**Mon**: courgette, chick pea and rosemary soup (Roddy)

**Tue**: puttanesca + green beans (Roddy)

**Wed**: dull dal

**Thu**: carrot soup

**Fri**: Coconut white fish curry + broccoli + potato (Sodha).

**Sat**: pasta e fagioli (Roddy)

**Sun**: ribollita with borlotti beans

**Drinks**: turmeric tea, coffee\
**Spices**: chilli, fennel, all spice, coriander, ginger, smoked paprika\
**Herbs**: rosemary, parsley, curry leaves, sage\
**Vegetables**: red onion, red pepper, spinach, rocket, onion, courgette, potato, tomato, olives, capers, sweet potato, parsnip, orange pepper, spinach, celeriac, lemon, carrot, coconut milk, broccoli, chard, cavolo nero, celery, garlic\
**Pulses / grains**: black beans, chick peas, oats, green lentils, red lentils, cannellini beans, borlotti beans\
**Nuts**: walnuts, pecans, brazil, almonds, pumpkin seeds, sesame paste\
**Fruit**: blueberry, pomegranate, banana\
**Other**: tofu, sauerkraut, vegetable stock

#### 50 Monday 13-01-2025 to Sunday 19-01-2025

**Mon**: Roast vegetables + baked potato

**Tue**: Noodle soup - forgot the noodles!, shrimps, scallops, broccoli, mushrooms, asparagus

**Wed**: Ethiopian lentil and spinach soup (Miers)

**Thu**: Langarwali dal - Gowardhan

**Fri**: Salmon + broccoli + red peppers + steamed potatoes

**Sat**: Courgette, chick pea, rosemary soup (Roddy).\

**Sun**: seafood stir-fy, peppers, green beans

**Drinks**: coffee, turmeric tea, peppermint tea\
**Spices**: chilli, cumin, coriander, ginger, berbere, asoefitida, garam masala, turmeric\
**Herbs**: coriander, rocket, water cress, rosemary\
**Vegetables**: cavolo nero, chard, tomato, celery, onion, red onion, aubergine, courgette, sweet potato, red pepper, shallot, carrot, spinach, mushrooms, asparagus, celeriac, parsnip, ps broccoli, yellow pepper, orange pepper\
**Pulses / grains**: borlotti beans, cannellini beans, chick peas, green lentils, red lentils, black urad dal, black beans\
**Nuts**: tahini, brazil, almond, pumpkin seeds\
**Fruit**: banana, blueberry, raspberry\
**Other**: sauerkraut, tofu, miso

#### 51 Monday 20-01-2025 to Sunday 26-01-2025

**Mon**: fasoulia (Sodha)

**Tue**: puy lentils + red pepper + stem broccoli (Iyer)

**Wed**: sea bass, roast cauliflower (Sodha), puy lentils

**Thu**: dull dal

**Fri**: seafood stir fry, red, yellow pepers, pak choi, noodles

**Sat**: lentil ragu (Roddy) + mashed potato topping + PS broccoli

**Sun**: leek, courgette soup

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: cumin, all spice, yellow mustard seeds, turmeric, chilli, ras el hanout, ginger, cumin, coriander\
**Herbs**: coriander, rocket, watercress, basil\
**Vegetables**: parsnip, celeriac, sweet potato, tenderstem broccoli, red pepper, tomato, onion, red onion, olives, cauliflower, spinach, lemon, pak choi, leek, PS broccoli, mushrooms\
**Pulses / grains**: puy lentils, cannellini beans, haricot beans, red lentils, green lentils, chick peas\
**Nuts**: cashew, brazil, almond, pumpkin seeds, pecan\
**Fruit**: banana, blueberry, raspberry\
**Other**: tofu, hummus\

#### 52 Monday 27-01-2025 to Sunday 02-02-2025

**Mon**: lentil ragu + tagliatelli + green beans

**Tue**: cod + peppers + tomato + berbere + broccoli

**Wed**: puttanesca + peas + spaghetti

**Thu**: patates yahni

**Fri**: chips!

**Sat**: courgette, chick pea, rosemary soup inc cavolo nero (Roddy).

**Sun**: pasta e fagioli (Roddy)

**Drinks**: turmeric tea, coffee, peppermint tea\
**Spices**: berbere, coriander, all spice, chilli\
**Herbs**: parsley, coriander, bay, rosemary, sage\
**Vegetables**: red cabbage, carrot, celeriac, red pepper, cucumber, mushroom, garlic, lemon, green beans, broccoli, peas, tomato, olives, rocket, water cress, sweet potato, parsnip, yellow pepper, capers, cavolo nero, courgette, kale, celery, onion, red onion\
**Pulses / grains**: chick peas, green lentils, black beans, cannellini beans\
**Nuts**: pecan, pumpkin seeds, tahini, cashew, brazil\
**Fruit**: raspberry, blueberry, banana, plums\
**Other**: tofu, sauerkraut, hummus\

#### 53 Monday 03-02-2025 to Sunday 09-02-2025

**Mon**: roasted red pepper and tomato soup + flatbread (Debs)

**Tue**: noodle soup: prawns, purple sprouting broccoli, red pepper

**Wed**: roast cauliflower, sprouts, shallots, potatoes, broccoli

**Thu**: stuffed aubergine + green beans

**Fri**: sea bass, broccoli, red peppers, pak choi, steamed potatoes

**Sat**: Ethiopian spinach and lentil (Miers)

**Sun**: noodle stir-fry: prawns, red peppers, mange-tout, spring onion

**Drinks**: coffee, turmeric tea, peppermint tea\
**Spices**: ginger, cumin, coriander, chilli, berbere\
**Herbs**: mint, coriander, basil\
**Vegetables**: red pepper, yellow pepper, tomato, red cabbage, carrot, red onion, celeriac, cucumber, sweet potato, cauliflower, shallots, purple sprouting broccoli, avocado, lime, olives, garlic, onion, aubergine, green beans, pak choi, broccoli, spring onion\
**Pulses / grains**: chick peas, kidney beans, oats\
**Nuts**: almond, pumpkin seeds, almond, pecan, cashew, tahini\
**Fruit**: banana, plum, pomegranate, raspberry, blueberry\
**Other**: tofu, sauerkraut\

#### 54 Monday 10-02-2025 to Sunday 16-02-2025

**Mon**: ribollita

**Tue**: baked potato + tuna, green lentils, broccoli, olives

**Wed**: courgette, leek, lentil soup

**Thu**: buccatini, fish, parsley, olives, capers (Roden)

**Fri**: VFT + stuffed red peppers + leeks + chick pea + sardine dip

**Sat**: chick pea + sardine dip (leftovers)

**Sun**: lentil, courgette, dill soup

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: chilli\
**Herbs**: coriander, rocket, parsley, dill, pak choi, osaka greens, mizuno greens\
**Vegetables**: sweet potato, parsnip, red onion, olives, cavolo nero, celery, carrot, garlic, lemon, tomato, orange pepper, broccoli, red pepper, avocado, celeriac, courgette, leek, onion, aubergine\
**Pulses / grains**: oats, green lentils, cannellini beans, chick peas, black beans, red lentils, mung dal\
**Nuts**: brazil, cashew, almond, tahini, walnut, pumpkin seeds, pecan\
**Fruit**: pomegranate, raspberry, blueberry, banana, satsuma\
**Other**: tofu, sauerkraut\

#### 55 Monday 17-02-2025 to Sunday 23-02-2025

**Mon**: monkfish stew (Brittany Ferries)

**Tue**: mackerel, broccoli

**Wed**: chick peas, white fish, sardine rillette (Cafe du Port)

**Thu**: prawns (Lannion Market) + cocos beans + sardine + Breton Fish stew (Brittany Ferries)

**Fri**: patates yahni (Jones)

**Sat**: leek, spinach, carrot, celery, parsley, lentil soup

**Sun**: dull dal (red lentils, potatoes, spinach)

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: all spice, chilli, onion seed, ras el hanout\
**Herbs**: mache, rocket, oregano, pak choi, osaka greens, mizuno greens, flat leaf parsley, lettuce\
**Vegetables**: sweet potato, onion, avocado, tomato, garlic, leek, celery, carrot, lemon, spinach, broccoli, red onion\
**Pulses / grains**: cocos beans, chick peas, red lentils, haricot beans\
**Nuts**: almond, hazel, walnut\
**Fruit**: satsuma, banana, raspberry, red grapes, white grapes\
**Other**: sauerkraut, tofu\

#### 56 Monday 24-02-2025 to Sunday 02-03-2025

**Mon**: peppers, red onion, baked potato, sea bass

**Tue**: chestnut, brown lentil soup

**Wed**: white fish curry (Sodha)

**Thu**: grilled mackerel, peppers, cauliflower (Soda) sweet potato, allotment salad

**Fri**: fasoulia (Sodha)

**Sat**: chickpea, courgette, potato, rosemary soup (Roddy)

**Sun**: aubergine moussaka (Zoe)

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: berbere, cumin, turmeric, chilli, all spice, cinnamon\
**Herbs**: rocket, pak choi, osaka greens, mizuno greens, parsley, coriander, rosemary\
**Vegetables**: red onion, sweet potato, celeriac, parsnip, red pepper, green pepper, yellow pepper, squash, cauliflower, spring onion, lemon, lime, onion, cavolo nero, courgette, potato, celery, mushroom, tomato, aubergine\
**Pulses / grains**: haricot beans, black-eyed beans, brown lentils, chick peas, black beans, cannellini beans\
**Nuts**: walnut, cashew, pumpkin seeds, pecan, brazil, almond, chestnuts, tahini\
**Fruit**: blueberries, raspberries, banana, satsuma, pomegranate, blackberries\
**Other**: tofu, sauerkraut, miso\

#### 57 Monday 03-03-2025 to Sunday 09-03-2025

**Mon**: pasta e fagioli

**Tue**: courgette, leek, lentil soup

**Wed**: carrot, sweet potato tagine

**Thu**: noodles with roast pepper, broccoli, prawns

**Fri**: dull dal - spinach, red lentils, potato, onion

**Sat**: minestroni (Miers)

**Sun**: kedgeree - haddock, spices, green beans, peas, rice

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: chilli, pepper flake, turmeric, cinnamon, sweet paprika, cumin, coriander, ginger\
**Herbs**: bay leaf, mint, flat leaf parsley, basil, rocket, pak choi, osaka greens, mizuno greens\
**Vegetables**: sweet potato, squash, aubergine, onion, courgette, lemon, tomato, parsnip, leek, carrot, red pepper, yellow pepper, garlic, brussels sprouts, cauliflower, savoy cabbage, celery, peas, green beans\
**Pulses / grains**: brown lentil, chick pea, cocos bean, red lentil, oats, cannellini beans\
**Nuts**: cashew, almond, pumpkin seed, tahini, walnut, pecan\
**Fruit**: melon, grapes, raspberry, blackberry, blueberry, banana, pomegranate\
**Other**: sauerkraut, tofu\

#### 58 Monday 10-03-2025 to Sunday 16-03-2025

**Mon**: noodles with roast pepper, broccoli, prawns

**Tue**: puttanesca + baked potato

**Wed**: courgette, leek, lentil, mint soup

**Thu**: japanese leaves, pak choi, sardines

**Fri**: kidney beans, onion, cavolo nero, red peppers

**Sat**: butter beans, leek, artichoke hearts, peas (Sodha)

**Sun**: noodles with roast pepper, pak choi, prawns

**Drinks**: peppermint tea, turmeric tea, coffee\
**Spices**: chilli, coriander, turmeric, cumin\
**Herbs**: mint, pak choi, osaka greens, mizuno greens\
**Vegetables**: tomato, olive, onion, red onion, yellow pepper, red pepper, broccoli, parsnip, celeriac, sweet potato, capers, courgette, leek, garlic, cavolo nero, cauliflower, sprouts, artichoke hearts, peas\
**Pulses / grains**: red lentils, black beans, oats, kidney beans, butter beans\
**Nuts**: cashew, almond, pumpkin seed, walnut, pecan\
**Fruit**: blueberry, banana, pomegranate, raspberry, blackberry, mango, satsuma\
**Other**: tofu, sauerkraut\

#### 59 Monday 17-03-2025 to Sunday 23-03-2025

patates yahni white fish + puttanesca Chettiar aubergine curry (Kochhar) Courgette, cannellini bean, rosemary soup (Roddy).

**Mon**: patates yahni (Jones)

**Tue**: leek, courgette soup

**Wed**: baked potato and roast vegetables

**Thu**: pasta e fagioli

**Fri**: Grilled veg (Viraj ) 😐

**Sat**: dull dal

**Sun**: salmon, new potatoes, green beans, red peppers, kimchi

**Drinks**: turmeric tea, peppermint tea, coffee\
**Spices**: chilli, cumin, fennel, all spice\
**Herbs**: coriander, pak choi, osaka greens, mizuno greens, parsley, bay, sage\
**Vegetables**: parsnip, celeriac, carrot, onion, courgette, leek, garlic, aubergine, tomato, celery, olives, lemon, artichoke, spinach, sweet potato, green beans\
**Pulses / grains**: oats, red lentils, green lentils, chick peas, cannelini beans\
**Nuts**: pecan, cashew, pumpkin seeds, brazil, walnut, almond, tahini\
**Fruit**: blueberries, raspberries, banana, pomegranate, satsuma\
**Other**: tofu, kimchi\

#### 60 Monday 24-03-2025 to Sunday 30-03-2025

**Mon**: noodle soup with prawns, courgette, red peppers, pak choi

**Tue**: squash, sweet potato soup

**Wed**: lentil, leek soup

**Thu**: sea bass, chips and peas

**Fri**: courgette, cannellini bean, rosemary soup (Roddy)

**Sat**: Shiitake, ginger, rice noodle broth (Sodha)

**Sun**: soba noodle, ginger, spring onions, salmom, + spinach

**Drinks**: turmeric tea, peppermint tea, coffee\
**Spices**: coriander, cumin, chilli, ginger, cinnamon, star anise\
**Herbs**: parsley, osaka greens, mizuno greens, rosemary, bay, coriander\
**Vegetables**: courgette, onion, garlic, red pepper, pak choi, purple sweet potato, parsnip, squash, peas, orange pepper, red onion, olives, broccoli, spring onion, shitake mushrooms, leek, spinach, avocado\
**Pulses / grains**: oats, black beans, cannellini beans, red lentils, chick peas\
**Nuts**: cashew, pecan, pumpkin seeds, almond, tahini **Fruit**: raspberry, banana, blueberry, satsuma, pomegranate\
**Other**: tofu, sauerkraut, vegetable stock, kimchi\

#### 61 Monday 31-03-2025 to Sunday 06-04-2025

**Mon**: white fish curry, tomatoes, coconut milk

**Tue**: cauliflower, potatoes and peas tray bake (Iyer Express)

**Wed**: ramen noodles, leeks

**Thu**: salmon, new potatoes, broccoli (picnic on train) - off to HK

**Fri**: aeroplane food: vegetable curry, brown lentils

**Sat**: hong kong goose, HK

**Sun**: tom yum soup at Shek O, HK

**Drinks**: turmeric tea, coffee\
**Spices**: pharos ?, chilli, smoked paprika, turmeric, lemon grass, kaffir lime leaf, galangal\
**Herbs**: parsley, osaka greens, mizuno greens, lettuce\
**Vegetables**: purple sweet potato, parsnip, tomato, olives, cauliflower, peas, potato, tomato, onion, garlic, bean sprouts, leek, cannellini beans\
**Pulses / grains**: chick peas, black beans, brown lentils\
**Nuts**: tahini, cashew, peanuts, peanut\
**Fruit**: blueberries, raspberries, pomegranate, banana, satsuma\
**Other**: tofu, sauerkraut\

#### 62 Monday 07-04-2025 to Sunday 13-04-2025

**Mon**: pad thai at Wong Chuk Tsuen (bike ride from HK)

**Tue**: mexican nachos, tacos, enchilladas at La Tagueros, HK

**Wed**: ramen noodles with fried tofu (HK airport)

**Thu**: smoked mackerel, lettuce, olives, potato (Heathrow)

**Fri**: ethiopian spinach, yellow split peas (Miers)

**Sat**: puttanesca, green beans

**Sun**: chick peas, harissa, preserved lemon (Ottolenghi Simple p262)

**Drinks**: coffee, peppermint tea\
**Spices**: chilli, ginger, cumin, cardamon, harissa\
**Herbs**: coriander, lemon grass, parsley\
**Vegetables**: corn, avocado, tomato, olive, lettuce, capers, spinach, parsnip, sweet potato, french beans, osaka greens, pak choi, lemon, onion, red onion\
**Pulses / grains**: cannellini beans, yellow split peas, oats, chick peas\
**Nuts**: peanuts, pecan, cashew, brazil, pumpkin seeds, almond\
**Fruit**: grapes, mango, water melon, gala melon, pomegranate, raspberry, blueberry\
**Other**: kimchi, tofu\

#### 63 Monday 14-04-2025 to Sunday 20-04-2025

**Mon**: Thai red sauce, shiitake mushrooms, green beans, pak choi, greens soup (Slater)

**Tue**: Stuffed aubergine + broccoli

**Wed**: noodles, pak choi, red pepper, mussels

**Thu**: pasta e fagioli (Roddy)

**Fri**: soba noodles, cabbage, tofu, osaka greens, ginger

**Sat**: parsnips, cabbage, leek, peppers, feta stir fried

**Sun**: white fish coconut curry (Sodha)

**Drinks**: coffee, peppermint tea, turmeric tea **Spices**: ginger, chilli, cumin, coriander, pepper flakes\
**Herbs**: coriander, lemon grass, parsley, oregano, bay, sage, winter purslane\
**Vegetables**: green beans, osaka greens, spring onion, shiitake mushroom, pak choi, aubergine, broccoli, garlic, parsnip, sweet potato, red pepper, olives, red onion, onion, cabbage, leek, yellow courgette, green courgette, yellow pepper, orange pepper, coconut milk, celeriac\
**Pulses / grains**: oats, green lentils, cannellini beans, butter beans, mung dal\
**Nuts**: pecan, brazil, almond, cashew, pumpkin seeds, tahini\
**Fruit**: pomegranate, blueberry, raspberry, banana, satsuma\
**Other**: thai red paste, vegetable stock, sauerkraut\

#### 64 Monday 21-04-2025 to Sunday 27-04-2025

**Mon**: olive, anchovy, artichoke hearts pizza (Hazan)

**Tue**: brown lentil ragu (Roddy) + cauliflower

**Wed**: dull dal

**Thu**: glass noodles, purple broccoli, peas, mushrooms, pak choi, red pepper

**Fri**: sea bass, potatoes, asparagus, grilled tomatoes, basil (Slater)

**Sat**: aubergine, lemon risotto (Ottolenghi, Plenty)

**Sun**: cannelini bean, mung bean, brown lentil, greens, ramen noodle soup (shaida p134)

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: smoked paprika, chilli, ginger, cumin, coriander, turmeric, berbere\
**Herbs**: osaka greens, dill, mint, rocket, basil, parsley\
**Vegetables**: cauliflower, artichike hearts, olive, tomato, celeriac, sweet potato, orange pepper, mushrooms, pak choi, parsnip, purple broccoli, red pepper, asparagus, aubergine, lemon, avocado, spinach\
**Pulses / grains**: oats, brown lentil, red lentils, cannellini beans, mung beans\
**Nuts**: cashew, pecan, brazil, tahini\
**Fruit**: banana, raspberry, blueberry, satsuma, pomegranate\
**Other**: tofu, vegetable stock\

#### 65 Monday 28-04-2025 to Sunday 04-05-2025

**Mon**: roast tomato, squash, sweet potato soup

**Tue**: brown lentil ragu, peas (Roddy)

**Wed**: salmon, broccoli

**Thu**: leek, courgette, mint soup

**Fri**: minestroni (debs)

**Sat**: potatoes, capers, salmon, olives, lentils

**Sun**: noodles, olives, capers, sardines, cannellini beans

**Drinks**: coffee, peppermint tea\
**Spices**: coriander, chilli, ginger\
**Herbs**: basil, coriander, parsley, mint\
**Vegetables**: sweet potato, squash, tomato, parsnip, onion, red onion, osaka greens, artichoke hearts, olive, mushroom, peas, courgette, leek, capers,\
**Pulses / grains**: cannellini beans, brown lentil, oats, black beans\
**Nuts**: cashew, brazil, walnut, pecan\
**Fruit**: raspberry, blueberry, banana, satsuma\
**Other**: tofu, sauerkraut\

#### 66 Monday 05-05-2025 to Sunday 11-05-2025

**Mon**: patates yahni (Jones)

**Tue**: ethiopian split peas and spinach (Miers)

**Wed**: noodle soup + prawns

**Thu**: lentil soup + mint, parsley

**Fri**: mushroom wellington, carrots, asparagus

**Sat**: cauliflower, peas, potato (Iyer)

**Sun**: green lentils, sardines, spring onion, tomato

**Drinks**: peppermint tea, coffee, turmeric tea\
**Spices**: onion seeds, chilli, all spice, cumin, coriander, ginger, fenugreek, fennel, mustard seeds\
**Herbs**: oregano, parsley, dill, mint, basil\
**Vegetables**: olives, tomato, onion, garlic, spinach, red pepper, yellow pepper, red onion, purple broccoli, pak choi, courgette, lime, celery, aubergine, cauliflower, peas, spring onion\
**Pulses / grains**: kidney beans, green lentils, yellow split peas, oats, red lentils, cannellini beans\
**Nuts**: brazil, pecan, cashew, almond\
**Fruit**: satsuma, banana, blueberries, raspberries, apple\
**Other**: tofu, sauerkraut\

#### 67 Monday 12-05-2025 to Sunday 18-05-2025

**Mon**: courgette soup

**Tue**: cannelini bean, mung bean, brown lentil, greens, ramen noodle soup (shaida p134)

**Wed**: sea bass, peas, new potatos

**Thu**: baked potato, puttanseca

**Fri**: courgette, basil, pasta salad

**Sat**: dull dal

**Sun**: courgette + noodle soup

**Drinks**: coffee\
**Spices**: turmeric\
**Herbs**: dill, basil, parsley, oregano\
**Vegetables**: courgette, parsnip, sweet potato, onion, garlic, tomato, olive, spinach, lemon, capers, peas, garlic\
**Pulses / grains**: red lentils, cannellini beans, mung beans, brown lentils, oats, edamame beans\
**Nuts**: pumpkin seeds, cashew, brazil, almond\
**Fruit**: banana, blueberry, raspberry, satsuma\
**Other**: tofu, sauerkraut\

#### 68 Monday 19-05-2025 to Sunday 25-05-2025

**Mon**: courgette + noodle soup

**Tue**: pasta e fagioli

**Wed**: pasta alla norma

**Thu**: chick pea, mung bean, brown lentil, greens, ramen noodle soup (shaida p134)

**Fri**: fish fingers and chips (tea for Martha and Wren)

**Sat**: courgette, lentil, herbs soup

**Sun**: pateates yahni (Jones)

**Drinks**: coffee, peppermint tea\
**Spices**: pepper flakes, chilli, turmeric, all spice\
**Herbs**: mint, basil, coriander, oregano, parsley, dill, onion seeds\
**Vegetables**: tomato, sweet potato, parsnip, aubergine, garlic, spinach, spring onion, onion, olive, courgette, cavolo nero, red onion\
**Pulses / grains**: cannellini beans, oats, chick peas, brown lentils, mung beans, red lentils\
**Nuts**: cashew, almond, brazil, pumpkin seeds, pecan\
**Fruit**: satsuma, banana, blueberry, raspberry\
**Other**: tofu, sauerkraut\

#### 69 Monday 26-05-2025 to Sunday 01-06-2025

**Mon**: roast peppers, herbs, squash, swee potato, beetroot (Roden)

**Tue**: leek, potato, courgette soup

**Wed**: leek, potato, courgette soup

**Thu**: tomato, red pepper soup (Cloake)

**Fri**: Spaghetti with prawns, courgettes and gremolata (Roddy)

**Sat**: squash, sweet potato soup, soba noodles

**Sun**: steamed trout, potatoes, peas

**Drinks**: peppermint tea, coffee\
**Spices**: chilli, cumin, coriander\
**Herbs**: basil, mint, parsley, dill, coriander\
**Vegetables**: sweet potato, spring onion, capers, olives, red pepper, beetroot, leek, courgette, tomato, avocado, lemon, lime, onion, red onion, broccoli, peas\
**Pulses / grains**: chickpeas, oats, red lentils, brown lentils, mung beans\
**Nuts**: pistachios, cashew, tahini, walnut, brazil\
**Fruit**: blueberries, raspberries, satsuma, pomegranate, banana\
**Other**:\

#### 70 Monday 02-06-2025 to Sunday 08-06-2025

**Mon**: Urad dal (Gowardhan)

**Tue**: White fish coconut curry (Sodha)

**Wed**: pea, courgette, leek soup

**Thu**: pea, courgette, leek soup

**Fri**: caremelised onion tart

**Sat**: barbecue - quorn type wrap

**Sun**: dull dal

**Drinks**: coffee, turmeric tea\
**Spices**: coriander, cumin, ginger, asafoetida, smoked paprika, chilli, ras el hanout\
**Herbs**: coriander, curry leaves\
**Vegetables**: sweet potato, squash, potato, tomato, lime, garlic, green beans, leek, peas, spinach, broccoli, courgette, red peppers\
**Pulses / grains**: urad dal, oats, red lentils\
**Nuts**: brazil, walnut, pumpkin seeds\
**Fruit**: banana, raspberries, blueberries, pomegranate\
**Other**: tofu, sauerkraut\

#### 71 Monday 09-06-2025 to Sunday 15-06-2025

**Mon**: patates yahni

**Tue**: courgettes, tomato , mussels + rigatoni

**Wed**: pasta e fagioli

**Thu**: Miso rice, peas, ginger and mint + leeks (Sodha).

**Fri**: white fish curry (Sodha)

**Sat**: vegetarian chilli, miso aubergines, roast cauliflower

**Sun**: soba noodles, ginger, sping onions

**Drinks**: coffee, peppermint tea\
**Spices**: all spice, ras el hanout, chilli\
**Herbs**: parsley, mint\
**Vegetables**: tomato, courgette, sweet potato, parsnip, olives, letuce, leek, spring onion, caper, peas, squash\
**Pulses / grains**: oats, cannellini beans\
**Nuts**: cashew, brazil, almond\
**Fruit**: blueberries, raspberries, banana\
**Other**: sauerkraut, tofu, miso paste\

#### 72 Monday 16-06-2025 to Sunday 22-06-2025

**Mon**: gozlem (driving to Heathrow)

**Tue**: courgette soup - leeks, mint, dill, red lentils

**Wed**: courgette, basil, pasta

**Thu**: grilled vegetables, steamed green beans

**Fri**: purple sprouting broccoli, green lentils, mussels, new potatos

**Sat**: fish and chips (The Queen's Head, Botallack)

**Sun**: roast vegetables, baked potato

**Drinks**: coffee, peppermint tea\
**Spices**: chilli\
**Herbs**: basil, dill, coriander, mint\
**Vegetables**: courgette, spring onion, onion, leek, lemon, capers, sweet potato, olives, red onion, padron peppers, orange pepper, green beans, aoubergine, red pepper, tomato\
**Pulses / grains**: red lentils, cannellini beans, chick peas, tahini, green lentils\
**Nuts**: brazil, almond, walnut, pecan\
**Fruit**: blueberries, banana, raspberries, pomegranate\
**Other**: tofu, sauerkraut\

#### 73 Monday 23-06-2025 to Sunday 29-06-2025

**Mon**: pea, potato, spinach and coconut curry (Gowardhan/Sodha)

**Tue**:cannellini bean, courgette, potato and rosemary soup (Roddy)

**Wed**: spring soup: green beans, spinach, peas, broad beans, courgette (Roddy)

**Thu**: linguini + puttanesca + mussels, prawns + purple sprouting broccoli

**Fri**: Everyday dal (Sodha)

**Sat**: Grilled padrons, red peppers, courgette, aubergine

**Sun**: Grilled red peppers, courgette, aubergine, sea bass, new potatoes

**Drinks**: coffee, turmeric tea, peppermint tea\
**Spices**: coriander, turmeric, cumin, chilli, ginger\
**Herbs**: bay, salad leaves, rosemary, sage, coriander, basil, curry leaves, dill\
**Vegetables**: red onion, onion, peas, spinach, potato, lemon, garlic, courgette, celery, broad beans, purple sprouting broccoli, capers, olives, tomato, red pepper, sweeet potato, padron peppers, aubergine\
**Pulses / grains**: cannellini beans, tahini, oats, chick peas, red lentils\
**Nuts**: pecan, walnut, brazil, cashew, pumpkin seeds\
**Fruit**: raspberry, blueberry, pomegranate, satsuma, nectarine\
**Other**: coconut milk, sauerkraut, kimchi\

#### 74 Monday 30-06-2025 to Sunday 06-07-2025

**Mon**: roast tomato soup (Cloake)

**Tue**: chick pea, rosemary, courgette, potato soup (Roddy)

**Wed**: patates yahni (Jones)

**Thu**: Ethiopian Berbere chard and yellow split pea with tomato (me) (Miers)

**Fri**: Salmon, orange and yellow peppers (camping)

**Sat**: dull dal

**Sun**: Romesco + leeks + cannellini + mung beans + flat breads (Sodha)

**Drinks**: coffee\
**Spices**: chilli, all spice, onion seeds, ginger, berbere\
**Herbs**: basil, coriander, rocket, rosemary, oregano, mint\
**Vegetables**: sweet potato, squash, tomato, onion, orange pepper, red onion, olives, lettuce, courgette, garlic, broad beans, lemon, yellow pepper, spinach, red pepper, leeks\
**Pulses / grains**: cannellini beans, oats, chick peas, butter beans, yellow split peas, red lentils, mung beans\
**Nuts**: brazil, cashew, pecan, walnut, pumpkin seeds\
**Fruit**: banana, raspberry, blueberry, pomegranate, apricot\
**Other**: tofu, kimchi\

#### 75 Monday 07-07-2025 to Sunday 13-07-2025

**Mon**: sea bass, potatoes, tomato, broad beans, olives

**Tue**: puttanesca

**Wed**: mung beans and hummus on bread

**Thu**: noodle soup + prawns, courgette

**Fri**: tinned red salmon, new potatoes, red peppers, olives

**Sat**: courgette, cannellini bean soup

**Sun**: salmon, steamed potatoes, beetroot, grill courgettte

**Drinks**: coffee\
**Spices**: coriander, cumin, chilli\
**Herbs**: basil\
**Vegetables**: broad beans, shallot, tomato, olives, leeks, tomatoes, capers, onion, red onion, beetroot, squash, green beans, peas, courgette, pak choi, garlic, red pepper, avocado, potatoes, cucumber\
**Pulses / grains**: mung beans, cannellini beans, oats, green lentils, black beans\
**Nuts**: cashew, brazil, pumpkin seeds\
**Fruit**: banana, pomegranate, blueberries, raspberries, apricot\
**Other**: tofu, miso\

#### 76 Monday 14-07-2025 to Sunday 20-07-2025

**Mon**: courgette soup

**Tue**: noodle soup with prawns, courgette, pak choi, peas

**Wed**: patates yahni + spinach

**Thu**: red lentil dal (Sodha)

**Fri**: salmon, salad, grilled courgettes and peppers, new potatoes

**Sat**: coconut, chard, peas, potato and broad bean curry

**Sun**: pasta, courgettes, tomato sauce, basil, mussels

**Drinks**: coffee, turmeric tea\
**Spices**: chilli, cumin, coriander, all spice, onion seeds, ginger, turmeric\
**Herbs**: parsley, mint, coriander, basil\
**Vegetables**: sweet potato, courgette, olives, tomato, onion, spring onion, cucumber, beetroot, carrot, celery, pak choi, red onion, peas, lemon, cherokee beans, garlic, lettuce, spinach, green beans, lettuce, capers, red pepper, chard, shallot\
**Pulses / grains**: oats, black beans, red lentils, cannellini beans, green lentils, chick peas\
**Nuts**: brazil, cashew, pumpkin seeds, almond, walnut\
**Fruit**: blackberry, blueberry, raspberry, banana\
**Other**: tofu, sauerkraut, kimchi\

#### 77 Monday 21-07-2025 to Sunday 27-07-2025

**Mon**: dull dal

**Tue**: minestroni (Roddy)

**Wed**: scrambled egg, peas, steamed potatoes

**Thu**: courgette, leek, mung dal soup + mint, coriander

**Fri**: 

**Sat**:

**Sun**: steamed white fish, carrots, potato

**Drinks**: coffee\
**Spices**: berbere, chilli\
**Herbs**: coriander, rosemary, basil, sage, bay, mint, parsley\
**Vegetables**: sweet potato, carrot, red onion, tomato, cucumber, onion, spinach, cabbage, parsnip, lettuce, courgette, potato, cherokee beans, celery, leek\
**Pulses / grains**: oats, red lentils, black beans, cannellini beans, mung dal, brown lentils\
**Nuts**: brazil, almond, pumpkin seeds, cashew\
**Fruit**: banana, raspberry, blueberry\
**Other**: tofu, sauerkraut\

#### 78 Monday 28-07-2025 to Sunday 03-08-2025

**Mon**: mackerel, cabbage, courgettes, potato

**Tue**: sea bass, cherokee beans, ratatouille, potatoes

**Wed**: sea bass, courgette, tomato, aubergine, potatoes

**Thu**: prawn roll, lettuce (Vietnamese shop in Lannion), sardines, lettuce, cannellini beans

**Fri**: caponata, risotto (Locquirec)

**Sat**: courgette soup

**Sun**: mackerel, potato, cucumber, tomato, lentils (camping)

**Drinks**: coffee\
**Spices**:\
**Herbs**: rosemary, parsley\
**Vegetables**: courgette, cabbage, red onion, tomato, cherokee beans, onion, lettuce, aubergine, cucumber, olives\
**Pulses / grains**: cocos beans, cannellini beans, brown lentils, chick peas\
**Nuts**: cashew, brazil, almond\
**Fruit**: plum, banana, peach, blueberry,apricot, cherries\
**Other**:\

#### 79 Monday 04-08-2025 to Sunday 10-08-2025

**Mon**: feta, cherokee beans, tomato

**Tue**: tuna, cherokee beans, tomato

**Wed**: tuna, cherokee beans, ratatouille, haricot beans

**Thu**: moules (self cooked), frites

**Fri**:

**Sat**: cocos beans, tomato, brown lentils

**Sun**: feta, cannellini beans, tomato, courgette

**Drinks**: coffee, peppermint tea\
**Spices**: cinnamon\
**Herbs**:\
**Vegetables**: capers, cherokee beans, red onion, onion, courgette, peas, tomato\
**Pulses / grains**: brown lentils, haricot beans, cannellini beans, cocos beans\
**Nuts**: hazelnut, cashew\
**Fruit**: apricot, peach, nectarine, mirabelle, raspberry, blackberry, cherry\
**Other**:\

#### 80 Monday 11-08-2025 to Sunday 17-08-2025

**Mon**: falafal, carrots

**Tue**: mackerel, haricot beans

**Wed**: mackerel, capers

**Thu**: oysters, herring, anchovies

**Fri**: mach (sheep's lettuce), red peppers, yellow peppers

**Sat**: courgette soup

**Sun**: patatas yahni (Jones)

**Drinks**: coffee, turmeric tea\
**Spices**: chilli, all spice, onion seeds, pepper flakes\
**Herbs**: parsley, oregano, bay, sage\
**Vegetables**: red pepper, sheep's lettuce, yellow pepper, tomato, courgette, potato, avocado, onion, red onion, avocado, capers, olives\
**Pulses / grains**: brown lentils, haricot beans, red lentils\
**Nuts**: pumpkin seeds, walnuts\
**Fruit**: apricot, peach, mirabelle, blueberry, raspberry\
**Other**: tofu\

#### 81 Monday 18-08-2025 to Sunday 24-08-2025

**Mon**: red lentils, tomato, potato, chard, spinach, berbere

**Tue**: pasta, tomato, red pepper soup (Cloake + pepper, pasta and fish sauce)

**Wed**: brown lentil, courgette, potato, rosemary soup (Roddy - ish)

**Thu**: caponata, steamed white fish, broccoli, potatoes

**Fri**: Courgette, chick pea, rosemary soup (Roddy).

**Sat**: tomato, padron pepper, bucatini

**Sun**: brown lentil ragu, roast sprouts

**Drinks**: coffee, turmeric tea\
**Spices**: chilli, berbere, fennel\
**Herbs**: parsley, sage, coriander, basil, bay, rosemary, mint\
**Vegetables**: tomato, olive, lemon, cucumber, red onion, lemon, garlic, chard, spinach, onion, cucumber, shallot, potato, red pepper, courgette, aubergine, celery, capers, beetroot, padron pepper, brussel sprouts, mushroom\
**Pulses / grains**: borlotti beans, chick peas, red lentils, brown lentils\
**Nuts**: cashew, walnut, pumpkin seeds, tahini, pine nut\
**Fruit**: blueberry, raspberry, banana, apricot, plum\
**Other**: sauerkraut\

#### 82 Monday 25-08-2025 to Sunday 31-08-2025

**Mon**: ribollita

**Tue**: courgette soup

**Wed**: pasta, tomato, red pepper soup (Cloake + red pepper, pasta)

**Thu**: red lentils, tomato, potato, chard, berbere

**Fri**: pasta + tomatoes, roast beetroot, caponata

**Sat**: cod, tomatoes, potatoes, grilled peppers, courgettes

**Sun**: cod, beetroot, caponata, tomato, cavolo nero, potato

**Drinks**: coffee, turmeric tea, peppermint tea\
**Spices**: chilli, berbere\
**Herbs**: mint, parsley, basil, coriander, rosemary\
**Vegetables**: courgette, tomato, cavolo nero, chard, onion, carrot, celery, aubergine, beetroot, red onion, olive, chard, red pepper, yellow pepper, orange pepper, avocado, rocket\
**Pulses / grains**: cannelini beans, kidney beans, red lentils, edamame beans\
**Nuts**: tahini, cashew, walnut, pine nut, pumpkin seeds\
**Fruit**: plum, apricot, raspberry, blueberry, blackberry\
**Other**: tofu, sauerkraut\

#### 83 Monday 01-09-2025 to Sunday 07-09-2025

**Mon**: black beans, peas, courgette, rice noodles

**Tue**: baked potato, roast vegetables

**Wed**: pasta e fagioli

**Thu**: potato, chard, peas and coconut (Sodha)

**Fri**: chick peas, cavolo nero (River Café blue)

**Sat**: courgette and mint pilau, plus pistachio greek yoghurt (Sodha)

**Sun**: ribollita

**Drinks**: coffee, peppermint tea\
**Spices**: chilli, ginger, red pepper flakes, cumin, coriander\
**Herbs**: rocket, parsley, rosemary, dill, mint\
**Vegetables**: peas, courgette, beetroot, olive, aubergine, garlic, potato, celery, onion, courgette, red pepper, yellow pepper, celery, chard, coconut, carrot, cavolo nero\
**Pulses / grains**: black beans, brown lentils, cannelini beans, chick peas\
**Nuts**: cashew, pine nuts, walnut, almond, pistachio\
**Fruit**: apple, blueberries, raspberries, banana, melon\
**Other**: miso, tofu\

#### 84 Monday 08-09-2025 to Sunday 14-09-2025

**Mon**: salmon, udon noodles, leeks, green beans

**Tue**: potato, chard, mushroom, coconut soup

**Wed**: courgette soup, glass noodles

**Thu**: rice, courgettes, broccoli, coriander

**Fri**: red lentil soup

**Sat**: chettiar aubergine curry, green beans (Kochhar)

**Sun**: noodle soup, prawns

**Drinks**: coffee, peppermint tea\
**Spices**: chilli, fennel, cumin\
**Herbs**: parsley, basil, coriander\
**Vegetables**: leek, green beans, garlic, olive, red pepper, chard, mushroom, courgette, carrot, celery, onion, tomato, yellow pepper, cucumber, broccoli, lemon, aubergine, green beans\
**Pulses / grains**: green lentils, black beans, red lentils\
**Nuts**: cashew, almond\
**Fruit**: apple, blueberry, pomegranate, raspberry, banana, fig\
**Other**: sauerkraut, tofu, miso\

#### 85 Monday 15-09-2025 to Sunday 21-09-2025

**Mon**: roast vegetable, baked potato

**Tue**: red lentil soup

**Wed**: roast squash, cauliflower, peppers, steamed potato

**Thu**: patates yahni

**Fri**: tomato soup, aubergine lasagne

**Sat**: mung dal, potatoes, chard

**Sun**: ribollita with cherokee beans, cavolo nero, cabbage

**Drinks**: peppermint tea, coffee, turmeric tea\
**Spices**: chilli, cumin, turmeric, onion seeds **Herbs**: coriander, parsley, basil, bay, sage, thyme\
**Vegetables**: sweet potato, red onion, rocket, watercress, spinach, cauliflower, squash, potato, red pepper, orange pepper, yellow pepper, chard, aubergine, leek, broccoli, carrot, celery, cavolo nero, savoy cabbage\
**Pulses / grains**: butter beans, black beans, red lentils, mung dal, cherokee beans\
**Nuts**: cashew, almond, pumpkin seeds, tahini, walnut\
**Fruit**: banana, blueberry, raspberry, pomegranate\
**Other**: tofu, sauerkraut\

#### 86 Monday 22-09-2025 to Sunday 28-09-2025

**Mon**: ribollita

**Tue**: puttanesca, covolo nero, peas

**Wed**: dull dal

**Thu**: roast squash, peppers, quinoa + tomato, cauliflower, tahini sauce

**Fri**: lentil soup with leek

**Sat**: fish pie (Roddy), green beans

**Sun**: fish pie, cavolo nero (à la 54 Queen Street) , aubergine + tomato (Moro easy)

**Drinks**: coffee, peppermint tea\
**Spices**: turmeric, chilli, cumin\
**Herbs**: basil, parsley\
**Vegetables**: squash, spinach, peas, red pepper, yellow pepper, orange pepper, tomato, red onion, onion, cauliflower, lemon, olives, garlic, capers, celery, leek, green beans, cavolo nero, aubergine\
**Pulses / grains**: cherokee beans, brown lentils, red lentils\
**Nuts**: cashew, almond, pecan, tahini\
**Fruit**: banana, raspberry, blueberry, apple\
**Other**: tofu, sauerkraut, vegetable stock\

#### 87 Monday 29-09-2025 to Sunday 05-10-2025

**Mon**: lentil, courgette soup

**Tue**: roast squash, chick peas, tofu, tomato

**Wed**: tomatoes, courgettes, capers, bucatini (River Café Easy)

**Thu**: noodle soup, prawns, chard

**Fri**: Vegetable pie (Carla's tart, Roddy)

**Sat**: chick peas, cavolo nero, onion, mussels, coriander, basil, chard

**Sun**: smoked basa, cannellini beans, pinto beans, coconut milk, rice (Cloake)

**Drinks**: peppermint tea, coffee\
**Spices**: cumin, chilli, turmeric, smoked paprika, all spice\
**Herbs**: parsley, basil, coriander\
**Vegetables**: courgette, onion, red onion, olive, tomato, red pepper, yellow pepper, lettuce, capers, garlic, chard, green beans, salad leaves, cavolo nero, watercress\
**Pulses / grains**: red lentils, chick peas, quinoa, black beans, cannelini beans, pinto beans\
**Nuts**: almond, hazelnut, pumpkin seeds, cashew\
**Fruit**: raspberry, blueberry, apple, banana, pomegranate\
**Other**: sauerkraut, tofu, vegetable stock, miso\

#### 88 Monday 06-10-2025 to Sunday 12-10-2025

**Mon**: dull dal

**Tue**: tomato sauce + cod, green beans (Roddy)

**Wed**: Vegetable moussaka (Miers)

**Thu**: lentil, courgette soup

**Fri**: sea bass, braised cavolo nero, roast peppers, squash, red onion

**Sat**: pasta e fagioli with chard (Roddy)

**Sun**: pizzette (Roddy), tomatos, broccoli

**Drinks**: coffee, peppermint tea\
**Spices**: ras el hanout, chilli\
**Herbs**: basil, parsley, sage, mint\
**Vegetables**: chard, spinach, potato, tomato, red onion, onion, green beans, aubergine, garlic, capers, olives, squash, cavolo nero, red pepper, green pepper, yellow pepper, celery, salad leaves, broccoli\
**Pulses / grains**:, red lentil, pinto beans, cannellini beans, oats\
**Nuts**: cashew, almond, walnut, pecan, pumpkin seeds\
**Fruit**: pomegranate, satsuma, blueberry, blackberry, apple\
**Other**: sauerkraut, tofu, vegetable stock\

#### 89 Monday 13-10-2025 to Sunday 19-10-2025

**Mon**: courgette, lentil soup

**Tue**: roast vegetables, baked potato

**Wed**: toor dal, red lentils, shallots, curry leaves (Iyer)

**Thu**: roast squash, peppers, cherokee beans, avocado

**Fri**: salmon, chips, cavolo nero, broccoli

**Sat**: chick peas, chard (River Café/Roddy)

**Sun**: patates yahni

**Drinks**: coffee, peppermint tea\
**Spices**: chilli, asafoetida, mustard seeds, turmeric\
**Herbs**: dill, parsley, coriander, mint, curry leaves, sage, bay\
**Vegetables**: tomato, parsnip, sweet potato, olive, red onion, onion, garlic, celery, courgette, aubergine, shallots, yellow pepper, red pepper, orange pepper, rocket, salad leaves, broccoli, cavolo nero, chard\
**Pulses / grains**: oats, red lentils, cherokee beans, toor dal, chick peas\
**Nuts**: cashew, almond, walnut\
**Fruit**: apple, blueberry, raspberry, pomegranate, banana\
**Other**: sauerkraut, tofu\

#### 90 Monday 20-10-2025 to Sunday 26-10-2025

**Mon**: courgette, lentil soup

**Tue**: noodle soup, prawns, courgettes

**Wed**: salmon, squash, peppers, brown lentils

**Thu**: pasta à la Norma, cavolo nero

**Fri**: tunisian vegetable stew (squash?) - Totnes

**Sat**: seafood paella (Dartmouth food fair)

**Sun**: lentils, coconut, sweet potato (Jones)

**Drinks**: coffee\
**Spices**: chilli, coriander, cumin, ginger, fennel, saffron, cardamon\
**Herbs**: bay, sage, parsley, coriander\
**Vegetables**: parsnip, sweet potato, red pepper, yellow pepper, green pepper, orange pepper, courgette, onion, red onion, caper, olive, garlic, tomato, celery, carrot, green beans, cavolo nero, aubergine, avocado, orange tomato, coconut\
**Pulses / grains**: red lentils, brown lentils, butter beans, black beans, chick peas, oats\
**Nuts**: walnut, pecan, cashew, almond\
**Fruit**: banana, satsuma, raspberry, blueberry, pomegranate\
**Other**: tofu, sauerkraut, vegetable stock\

#### 91 Monday 27-10-2025 to Sunday 02-11-2025

**Mon**: vegetable lasagne (Jones)

**Tue**: linguini, prawns, tomato (Roden)

**Wed**: fishfingers, chard, cavolo nero, broccoli

**Thu**: orzo, leek, yoghurt, herbs (Jones)

**Fri**: dal, coconut, tomato (Jones)

**Sat**: brown lentil, chestnut soup (Roddy)

**Sun**: fish curry (Sodha), peas, cavolo nero

**Drinks**: coffee, turmeric tea\
**Spices**: cardamon, chilli, smoked paprika, sumac, coriander, cumin\
**Herbs**: basil, parsley, sage, bay, rosemary, mint, coriander, currry leaves, pandan\
**Vegetables**: tomato, capers, olives, sweet potato, tamarind, lemon, chard, cavolo nero, red onion, onion, broccoli, potato, leek, coconut, beetroot, rocket, spinach, peas\
**Pulses / grains**: red lentils, brown lentils, borlotti beans, oats\
**Nuts**: cashew, almond, walnut, chestnut\
**Fruit**: satsuma, blueberry, pomegranate, raspberry, blackberry\
**Other**: tofu, sauerkraut\

#### 92 Monday 03-11-2025 to Sunday 09-11-2025

**Mon**: brown lentil ragu, broccoli

**Tue**: red lentil, coconut dal (Thompson)

**Wed**: fish fingers, chick peas, tomato

**Thu**: cannellini beans, courgettes

**Fri**: patates yahni, purple sprouting broccoli (Jones)

**Sat**: chick pea, coconut spinach

**Sun**: vegetable couscous, broccoli, tomato (Roden)

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: garam masala, coriander, ginger, turmeric, cinnamon, mustard seeds, fennel\
**Herbs**: curry leaves, dill, parsley, coriander\
**Vegetables**: broccoli, orange pepper, beetroot, red onion, olives, tomato, peas, garlic, spinach, coconut milk, orange pepper, courgette, cavolo nero, chard, aubergine, squash, red pepper\
**Pulses / grains**: brown lentils, oats, red lentils, cannellini beans, chick peas\
**Nuts**: walnut, cashew, pumpkin seeds\
**Fruit**: raspberry, blueberry, banana, pomegranate, satsuma, blackberry\
**Other**: tofu, sauerkraut\

#### 93 Monday 10-11-2025 to Sunday 16-11-2025

**Mon**: urad dal, coconut, broccoli, roast peppers

**Tue**: mussels, tomato jam, baked potato, cannellini beans

**Wed**: cannellini beans, avocado, salad leaves

**Thu**: cannellini beans, courgette, coconut, ginger

**Fri**: prawns, bucatini, green beans (Roden)

**Sat**: winter vegetable stew

**Sun**: winter vegetable stew

**Drinks**: coffee, peppermint tea, turmeric tea\
**Spices**: turmeric, cinnamon, garam masala, chilli, cumin, coriander, ginger, harissa\
**Herbs**: coriander, parsley\
**Vegetables**: squash, red pepper, yellow pepper, orange pepper, aubergine, carrot, onion, garlic, tomato, spinach, broccoli, red onion, salad leaves, coconut, courgette, green beans, celeriac, yellow carrot, cavolo nero\
**Pulses / grains**: black urad dal, chick peas, oats, cannellini beans, butter beans\
**Nuts**: walnut, almond, cashew, pumpkin seeds\
**Fruit**: banana, blueberry, pomegranate, raspberry, satsuma\
**Other**: tofu, miso\

#### 94 Monday 17-11-2025 to Sunday 23-11-2025

**Mon**: spiced vegetable soup (Persiana)

**Tue**: patates yahni (Jones)

**Wed**: baked potato, salmon, green beans

**Thu**: stuffed aubergine, pinto beans, herbs, anchovy, panko

**Fri**: fish curry (Sodha)

**Sat**: chick pea, coconut dal, chard, romanesco

**Sun**: red onion, peas and chard pie (Jones)

**Drinks**: turmeric tea, coffee\
**Spices**: all spice, chilli, smoked paprika, turmeric, coriander, cumin\
**Herbs**: coriander, parsley, dill, basil, sage, bay\
**Vegetables**: leeks, courgette, squash, tomato, onion, chard, celeriac, sweet potato, red pepper, tomato, olive, aubergine, garlic, lime, red onion, peas, coconut, lemon, romanesco\
**Pulses / grains**: chick peas, butter beans, pinto beans, kidney beans, oats\
**Nuts**: walnut, cashew, pumpkin seeds, almond\
**Fruit**: raspberry, blueberry, banana, satsuma, pomegranate\
**Other**: tofu, vegetable stock\

#### 95 Monday 24-11-2025 to Sunday 30-11-2025

**Mon**: red onion, peas and chard pie, romanesco, mash (Jones)

**Tue**: spiced vegetable soup (Persiana), green beans

**Wed**: sea bass, chips, peppers, peas

**Thu**: courgette soup, coconut

**Fri**: pizza, green salad(Bertinet)

**Sat**: stuffed aubergine, falafal, braised chard + avolo nero

**Sun**:

**Drinks**: coffee, peppermint tea\
**Spices**: chilli, coriander\
**Herbs**: parsley, bay, sage, rosemary\
**Vegetables**: peas, red onion, tomatoes, romanesco, chard, cavolo nero, courgette, sweet potato, celeriac, onion, red pepper, yellow pepper, green beans, squash, peas, yelllow carrot, olives, salad leaves\
**Pulses / grains**: chick peas, brown lentils, red lentils, oats\
**Nuts**: cashew, walnut, pumpkin seeds\
**Fruit**: satsuma, banana, raspberry, blueberry, pomegranate\
**Other**: tofu\

#### 96 Monday 01-12-2025 to Sunday 07-12-2025

**Mon**:

**Tue**:

**Wed**:

**Thu**:

**Fri**:

**Sat**:

**Sun**:

**Drinks**:\
**Spices**:\
**Herbs**:\
**Vegetables**:\
**Pulses / grains**:\
**Nuts**:\
**Fruit**:\
**Other**:\

#### 97 Monday 08-12-2025 to Sunday 14-12-2025

**Mon**:

**Tue**:

**Wed**:

**Thu**:

**Fri**:

**Sat**:

**Sun**:

**Drinks**:\
**Spices**:\
**Herbs**:\
**Vegetables**:\
**Pulses / grains**:\
**Nuts**:\
**Fruit**:\
**Other**:\

#### 98 Monday 15-12-2025 to Sunday 21-12-2025

**Mon**:

**Tue**:

**Wed**:

**Thu**:

**Fri**:

**Sat**:

**Sun**:

**Drinks**:\
**Spices**:\
**Herbs**:\
**Vegetables**:\
**Pulses / grains**:\
**Nuts**:\
**Fruit**:\
**Other**:\

#### 99 Monday 22-12-2025 to Sunday 28-12-2025

**Mon**:

**Tue**:

**Wed**:

**Thu**:

**Fri**:

**Sat**:

**Sun**:

**Drinks**:\
**Spices**:\
**Herbs**:\
**Vegetables**:\
**Pulses / grains**:\
**Nuts**:\
**Fruit**:\
**Other**:\

#### 100 Monday 29-12-2025 to Sunday 04-01-2026

**Mon**:

**Tue**:

**Wed**:

**Thu**:

**Fri**:

**Sat**:

**Sun**:

**Drinks**:\
**Spices**:\
**Herbs**:\
**Vegetables**:\
**Pulses / grains**:\
**Nuts**:\
**Fruit**:\
**Other**:\

**Coming week ideas**\
——————————————————————————.\
Prawns + harissa (Moro) + stuffed tomato\
Ottolenghi ratatouille\
Pasta e fagioli\
Stuffed aubergine\
Baccoumi (braised peppers, potato)\
——————————————————————————

**Favourites**

Roast squash + red onions/red peppers + cauliflower/celeriac + cannellini bean mash.\
Ethiopian Berbere spinach and green split pea with tomato (me) (Miers).\
Patates yahni (olives, potato, tomato) (Jones).\
Miso rice, peas, ginger and mint + roast red peppers (Sodha).\
Miso maple-glazed aubergine.\
dull dal = lentils + potato + spinach + ras el hanout.\
Urad dal + ras el hanout + pak choi.\
Minestrone (Roddy) courgette; chard; celery, carrots.\
Pasta e fagioli (Roddy).\
Pearl barley + celery + carrot.\
Split peas + black beans + roast squash + tomatoes + ras el hanout stew.\
Romesco + leeks + cannellini + black beans + flat breads (Sodha).\
Miso vegetable broth (Slater).\
Ottolenghi ratatouille.\
Brown lentil and mushroom ragu.\
Pasta + courgette + edamame beans + basil (Ottolenghi).\
Puttanesca.\
Caponata (Roddy) = aubergines, tomatoes, olives.\
Roast aubergine, pea and haddock kedgeree.\
Cod in tomato sauce with capers and olives + roast sprouts + rice (Roddy).\
Coconut white fish curry + broccoli + quinoa (Sodha).\
Noodle soup with prawns + (spinach, courgette, pak choi, mange tout, peppers).\
Prawns + harissa (Moro).\
brown lentil, yellow courgette, cavolo nero soup (Roddy-ish).\
Courgette, cannellini bean, rosemary soup (Roddy).\
Pasta alla Norma (Ottolenghi).\
Chettiar aubergine curry (Kochhar).\
Fasoulia = Iraqi white bean stew (Sodha)\
Shiitake, ginger, rice noodle broth (Sodha)\
Soba noodles, ginger, spring onions chick peas, harissa, preserved lemon (Ottolenghi Simple p262)\
pea, potato, spinach and coconut curry (Gowardhan)\
courgette and mint pilau, plus pistachio greek yoghurt (Sodha)\

**Template**

**Drinks**: \
**Spices**: \
**Herbs**: \
**Vegetables**: \
**Pulses / grains**:\
**Nuts**: \
**Fruit**: \
**Other**:
