---
title: "Ottolenghi ragu traybake"
format: html
editor: visual
---

-   3 carrots, peeled and chopped into large chunks (250g).
-   2 onions, peeled and chopped into large chunks (300g).
-   300g oyster mushrooms, roughly chopped
-   60g dried porcini, roughly blitzed
-   4 garlic cloves, crushed
-   3–4 plum tomatoes, chopped into large chunks (350g)
-   120ml olive oil
-   70g white miso paste
-   40g rose harissa (adjust according to the brand you are using)
-   4 tbsp tomato paste
-   90ml soy sauce
-   2 tsp cumin seeds, crushed
-   180g dried brown or green lentils
-   100g pearl barley
-   1 litre vegetable or chicken stock
-   160g coconut cream
-   100ml red wine
-   salt and black pepper

1.  Preheat the oven to 190°C fan.

2.  Working in batches, put the first six ingredients into a food processor and pulse until everything is very finely chopped (or very finely chop everything by hand if you don’t have a food processor).

3.  Put the chopped vegetables into a large, 36cm x 28cm non-stick high-sided baking tray with the oil, miso, harissa, tomato paste, soy sauce and cumin seeds and mix very well. Bake for 40 minutes, stirring halfway through, until browned around the edges and bubbling.

4.  Reduce the heat to 180°C fan.

5.  Add all the remaining ingredients to the tray, along with 150ml of water, ⅓ teaspoon of salt and a very generous grind of black pepper. Stir very well, scraping the crispy sides and bottom with a spatula. Cover tightly with foil and bake for another 40 minutes. Remove the foil and bake for a final 5 minutes. Set aside to rest for 15 minutes for the sauce to be absorbed a little before serving.
